using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using Bladex.Garantias.Infrastructure.DomainBase;
using Bladex.Garantias.Infrastructure.Logging;

namespace Bladex.Garantias.Infrastructure.RepositoryFramework
{
    /// <summary>
    /// Abstract class used to define the functionality and implementation of a <see cref="Bladex.Garantias.Infrastructure.RepositoryFramework.IRepository{T}"/>
    /// </summary>
    /// <typeparam name="T"><see cref="EntityBase"/> class</typeparam>
    public abstract class RepositoryBase<T>
        : IRepository<T>, IUnitOfWorkRepository where T : EntityBase
    {
        private IUnitOfWork unitOfWork;

        private Bladex.Garantias.Infrastructure.Logging.ILogger _logger = Bladex.Garantias.Infrastructure.Logging.ApplicationLogger.Instance;

        protected RepositoryBase()
            : this(null)
        {
        }

        protected RepositoryBase(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        #region IRepository<T> Members

        public abstract T FindBy(object key);

        public abstract IList<T> GetAll();

        public abstract long Count();

        public T Add(T item)
        {
            
            if (item.Key == null || !item.KeyAutoGenerated)
            {
                try
                {
                    // Insert 
                    if (this.unitOfWork != null)
                    {
                        this.unitOfWork.RegisterAdded(item, this);
                    }
                    else
                    {
                        return this.PersistNewItem(item);
                    }
                }
                catch (Exception ex)
                {
                    _logger.Error(string.Format("Error insertando entidad en {0}", this.GetType().Name), ex);
                    throw;
                }
            }
            else
            {
                try
                {
                    // Update
                    if (this.unitOfWork != null)
                    {
                        this.unitOfWork.RegisterChanged(item, this);
                    }
                    else
                    {
                        return this.PersistUpdatedItem(item);
                    }
                }
                catch (DBConcurrencyException dbEx)
                {
                    _logger.Warn(dbEx.Message, dbEx);
                    throw;
                }
                catch (Exception ex)
                {
                    _logger.Error(string.Format("Error actualizando entidad con Key {0} en {1}", item.Key, this.GetType().Name), ex);
                    throw;
                }
            }
            return item;
        }

        public void Remove(T item)
        {
            if (this.unitOfWork != null)
            {
                this.unitOfWork.RegisterRemoved(item, this);
            }
            else
            {
                this.PersistDeletedItem(item);
            }
        }

        public T this[object key]
        {
            get
            {
                return this.FindBy(key);
            }
            set
            {
                if (this.FindBy(key) == null)
                {
                    this.Add(value);
                }
                else
                {
                    this.unitOfWork.RegisterChanged(value, this);
                }
            }
        }

        #endregion

        #region IUnitOfWorkRepository Members

        public virtual EntityBase PersistNewItem(EntityBase item)
        {
            return this.PersistNewItem((T)item);
        }

        public virtual EntityBase PersistUpdatedItem(EntityBase item)
        {
            return this.PersistUpdatedItem((T)item);
        }

        public virtual void PersistDeletedItem(EntityBase item)
        {
            this.PersistDeletedItem((T)item);
        }

        #endregion

        protected IUnitOfWork UnitOfWork
        {
            get { return this.unitOfWork; }
        }

        protected abstract T PersistNewItem(T item);
        protected abstract T PersistUpdatedItem(T item);
        protected abstract void PersistDeletedItem(T item);
    }


}
