CREATE TABLE [dbo].[IMPORT_FCC_DEAL_HISTORY_H] (
    [FIC_MIS_DATE]      DATETIME     NULL,
    [TIME_ID]           NUMERIC (8)  NULL,
    [DEAL_REF]          VARCHAR (16) NULL,
    [PRODUCT_GROUP]     VARCHAR (6)  NULL,
    [DEAL_STAT_FROM_DT] DATETIME     NULL,
    [DEAL_CLOSURE_DATE] DATETIME     NULL,
    [EFFECTIVE_DATE]    DATETIME     NULL
);



