using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Bladex.Garantias.Infrastructure.DomainBase
{
    /// <summary>
    /// Clase abstracta que debe ser heredad por toda entidad del modelo.
    /// </summary>
    public abstract class EntityBase
    {
        
        private object key;
        protected bool _keyAutoGenerated = true;

        public bool KeyAutoGenerated
        {
            get { return _keyAutoGenerated; }
            set { _keyAutoGenerated = value; }
        }

        [NonSerialized()]
        private bool _isDirty = true;

        /// <summary>
        /// Default constructor
        /// </summary>
        protected EntityBase() :this(null)
        {
        }

        /// <summary>
        /// Overloaded constructor
        /// </summary>
        /// <param name="key">An <see cref="System.Object"/> thats represents the primary identifier 
        /// value for the class</param>
        protected EntityBase(object key)
        {
            this.key = key;
        }

        /// <summary>
        /// An <see cref="System.Object"/> that represents the primary identifier value for the class.
        /// </summary>
        public object Key
        {            
                get 
                { 
                    if(this.key != null && this.key.GetType()== typeof(Int64))
                        return Convert.ToInt32(this.key);  
                    else
                        return this.key;  
                }                
                set { this.key = value; }                       
        }

        /// <summary>
        /// Metodo generico que nos devuelve el Key convertido al tipo <typeparamref name="T"/>
        /// </summary>
        /// <typeparam name="T"><see cref="Type"/> al cual deseamos convertir el Key.</typeparam>
        /// <returns>Key de la entidad.</returns>
        public T GetKeyAs<T>()
        {
            T result = default(T);
            if (this.Key != null)
            {
                if (result is Int32)
                {
                    var o = Activator.CreateInstance(typeof(T));
                    o = Convert.ToInt32(this.Key);
                    return (T)o;
                }
                else
                {
                    result = (T) this.Key;
                }
            }
            return result;
        }

        /// <summary>
        /// Propiedad que determina si la entidad esta incompleta o no.
        /// </summary>
        public bool IsDirty
        {
            get { return this._isDirty; }
            set { this._isDirty = value; }
        }
        #region Equality Tests

        /// <summary>
        /// Determines whether the specified entity is equal to the current instance.
        /// </summary>
        /// <param name="entity">An <see cref="System.Object"/> that will be compared to the current instance.</param>
        /// <returns>True if the passed entity is equal to the current instance.</returns>
        public override bool Equals(object entity)
        {
            if(entity == null || !(entity is EntityBase))
            {
                return false;
            }
            return (this == (EntityBase)entity);
        }

        /// <summary>
        /// Operator overload for determining equality
        /// </summary>
        /// <param name="base1">The first instance of a <see cref="EntityBase"/>.</param>
        /// <param name="base2">The second instance of a <see cref="EntityBase"/>.</param>
        /// <returns>True if equal.</returns>
        public static bool operator ==(EntityBase base1, EntityBase base2)
        {
            if ((object)base1 == null && (object)base2 == null)
                return true;

            if ((object)base1 == null || (object)base2 == null)
                return false;

            return base1.GetHashCode() == base2.GetHashCode();
        }

        /// <summary>
        /// Operator overload for determining inequality
        /// </summary>
        /// <param name="base1">The first instance of a <see cref="EntityBase"/>.</param>
        /// <param name="base2">The second instance of a <see cref="EntityBase"/>.</param>
        /// <returns>True if not equal.</returns>
        public static bool operator !=(EntityBase base1, EntityBase base2)
        {
            return (!(base1 == base2));
        }

        /// <summary>
        /// Servers as a hash function for this type
        /// </summary>
        /// <returns>A hash code for the current Key property.</returns>
        public override int GetHashCode()
        {
            return this.key != null ? this.key.GetHashCode() : base.GetHashCode();
        }

        #endregion

        

    }
}
