-- =============================================
-- Script Template
-- =============================================

--SB56

INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'NA', N'NA')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'500', N'Banco Nacional de Panamá')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'501', N'Caja de Ahorros')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'505', N'Banco General, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'507', N'Primer Banco del Istmo, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'508', N'Banistmo Capital Markets Group, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'510', N'Banco Cuscatlán de Panamá S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'511', N'Metrobank, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'512', N'Banco Panameño de la Vivienda, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'513', N'Credicorp Bank, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'514', N'Banco Aliado, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'520', N'Banco Disa (En liquidación)')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'521', N'BNP Paribas Sucursal Panamá S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'523', N'Bancafé (Panamá), S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'525', N'Bancolombia (Panamá), S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'526', N'GNB Sudameris Bank')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'527', N'Banco Internacional de Costa Rica, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'528', N'HSBC Investment Corp. (Panamá), S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'529', N'Banco Santander (Panamá), S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'530', N'Bac International Bank, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'531', N'BCT Bank International, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'532', N'Banco de Bogotá, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'533', N'Popular Bank, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'534', N'Citibank N.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'535', N'Stanford International Bank (Panamá)')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'536', N'BNP Wealth Management ')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'537', N'Banesco, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'538', N'Fiduciaria Lafise, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'546', N'Assets Trust & Corporate Services, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'547', N'Fiduciaria Mossfon, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'548', N'Gala Trust and Management Services, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'549', N'Icaza Trust Corporation')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'550', N'MMG Fiduciary & Trust Corp.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'551', N'Alemán, Cordero, Galindo & Lee Trust (Panamá), S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'552', N'Sucre, Arias & Reyes Trust Services, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'553', N'ABS Trust, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'554', N'Quijano Trust Corporation')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'555', N'Swiss Arifa Trust Company')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'556', N'FMM Trust, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'557', N'Eskimor Trust Corp.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'565', N'Aseguradora Mundial, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'566', N'ASSA Compañía de Seguros, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'570', N'Towertrust, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'571', N'Global Financial Funds Corporation')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'572', N'Profuturo - Administradora de Fondos de Pensiones y Cesantía, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'573', N'La Hipotecaria, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'574', N'Trust Services, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'575', N'Credicorp Fondos de Pensiones y Cesantías, S.A')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'576', N'Progreso - Administradora Nacional de Fondos de Jubilaciones, Pensiones y Cesantías, S.A')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'577', N'Confederación Latinoaméricana de Cooperativas de   Ahorro y Crédito (COLAC)')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'578', N'Cooperativa de Servicios Múltiples Profesionales, R.L.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'579', N'Tac International Inc., S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'580', N'Financial Warehousing of Latin America')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'581', N'Overseas Management Trust Services')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'582', N'The General Trust Company, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'583', N'BG Trust, Inc')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'584', N'Auto Trust, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'585', N'Panacorp Fideicomisos S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'586', N'Mundial Servicios Fiduciarios, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'587', N'Multi Trust, Inc.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'588', N'Central Latinoamericana de Valores, S.A. (LATINCLEAR)')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'589', N'Panatrust International, S.A.')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'598', N'Sin Fiduciarias')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'599', N'Fiduciaria en el Exterior')
INSERT [dbo].[Fiduciarias] ([ID], [Nombre]) VALUES (N'NA', N'No Fiduciaria')
