-- =============================================
-- Script Template
-- =============================================

-- SB59
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0101', N'Vehículo Particular', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0102', N'Vehículo Comercial', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0103', N'Moto Particular', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0104', N'Moto Comercial', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0105', N'Flotas', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0106', N'Equipo Industrial', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0107', N'Equipo Agrícola', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0108', N'Equipos varios ', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0110', N'Naves (Barco o Transporte Marítmo) sin registro', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'01NA', N'N/A', N'01')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0201', N'Terreno', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0202', N'Terreno y edificación', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0203', N'Edificación', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0204', N'Propiedad Horizontal', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0205', N'Aeronaves', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0206', N'Naves (Barco o Transporte Marítmo) con registro', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'02NA', N'N/A', N'02')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0301', N'Depósitos en el Banco', N'03')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'03NA', N'N/A', N'03')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0401', N'Depósitos en Otros Bancos', N'04')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'04NA', N'N/A', N'04')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0501', N'Instrumentos Financieros', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0502', N'Derivados', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0503', N'Prenda Agraria', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0504', N'Prenda Ganadera', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0505', N'Prenda Mercantil ', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'05NA', N'N/A', N'05')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0601', N'Carta de Crédito de exportación / importación irrevocables', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0602', N'Cartas de Créditos "Stand By"', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0603', N'Cesiones sobre pagarés (claves de descuentos - Jubilados)', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0604', N'Fianzas y Avales Bancarios', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0605', N'Fianzas y Avales no  Bancarios', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'0606', N'Metales y piedras preciosas', N'06')
INSERT [dbo].[TipoGarantiaSuper] ([ID], [Nombre], [IdCategoriaSuper]) VALUES (N'06NA', N'N/A', N'06')