-- =============================================
-- Script Template
-- =============================================

--SB01 y SB39

INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'NA', N'NA', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'001', N'Banco Nacional de Panamá', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'002', N'Caja de Ahorros', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'003', N'Banco General, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'007', N'Bancafé (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'010', N'Banco Trasatlántico, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'013', N'Banco de Bogotá, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'020', N'MiBanco, S.A. BMF', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'024', N'Banco Internacional de Costa Rica, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'027', N'Banco Latinoamericano de Exportaciones, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'031', N'Banesco Banco Universal, C. A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'037', N'Citibank, N.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'039', N'Korea Exchange Bank, Ltd.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'045', N'The Bank Of Nova Scotia', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'050', N'Banco Aliado, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'051', N'Mega International Commercial Bank Co. Ltd.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'056', N'Towerbank International, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'059', N'Banco Panameño de la Vivienda, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'065', N'Bank Leumi-Le Israel, B.M.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'068', N'Banco Bilbao Vizcaya Argentaria (Panamá),S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'071', N'Blubank, Ltd.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'072', N'Banco de Crédito Helm Financial Services (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'075', N'Bancolombia (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'076', N'Banco de Bogotá, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'078', N'Bancafé (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'079', N'GNB Sudameris Bank, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'087', N'Banco de la Nación Argentina', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'093', N'GTC Bank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'095', N'Banco del Pacífico (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'106', N'International Union Bank, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'108', N'Banco de Occidente (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'111', N'Popular Bank Ltd., Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'114', N'ES Bank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'116', N'Banco Agrícola (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'117', N'Bank of China Limited', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'119', N'Banco de Crédito del Perú', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'125', N'Banco de Finanzas (Internacional), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'127', N'Atlantic Security Bank', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'135', N'Multibank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'136', N'Metrobank, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'140', N'Credicorp Bank, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'148', N'Global Bank Corporation', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'152', N'Banco Universal, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'153', N'Austrobank Overseas (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'155', N'BAC International Bank Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'173', N'MMG Bank Corporation', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'174', N'BAC Bank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'177', N'BNP Paribas Sucursal Panamá', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'179', N'Banco Citibank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'180', N'Banco Santander ( Panamà ), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'182', N'HSBC Bank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'184', N'Corficolombiana (Panamà) , S. A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'185', N'St. Georges Bank & Company, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'186', N'Banco Azteca (Panamá) S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'188', N'First Central International Bank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'189', N'FPB Bank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'190', N'Stanford Bank (Panamá), S.A. - Bajo Reorganización (Art. 141 de la Ley Bancaria)', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'191', N'TAG Bank, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'192', N'Produbank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'193', N'Banco Colpatria-Red Multibanca Colpatria, S.A., Sucursal Panamá', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'194', N'BNP Paribas Wealth Management', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'195', N'Banco Pichincha Panamá, S. A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'196', N'Banco Delta, S.A. (BMF)', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'197', N'Scotiabank Perú, S.A.A. Sucursal Panamá', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'198', N'Banco Lafise Panamá, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'199', N'BHD International Bank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'201', N'Banesco, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'203', N'Primer Banco del Istmo, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'205', N'Natixis', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'206', N'Banco de Guayaquil (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'210', N'Capital Bank, Inc.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'215', N'Mercantil Bank (Panamá), S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'220', N'Banco Panamá, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'221', N'Banco Financia, S.A. (BMF)', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'224', N'Banco Credit Andorra (Panamá), S. A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'225', N'BCT Bank International, S.A.', N'Local')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E001', N'A.B.N. AMRO BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E002', N'ALLIED IRISH BANKS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E003', N'AMERICAN EXPRESS BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E004', N'BANCO DEL AUSTRO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E005', N'BAC', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E006', N'BANCA NAZIONALE DEL LAVORO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E007', N'BANCAFE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E008', N'BANCO BILBAO VIZCAYA ARGENTARIA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E009', N'BANCO CENTROAMERICANO DE INTEGRACION ECONOMICA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E010', N'BANCO COOPERATIVO SICREDI S.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E012', N'BANCO DAVIVIENDA S.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E014', N'BANCO DE CREDITO E INVERSIONES', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E015', N'BANCO DE GALICIA Y BUENOS AIRES', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E016', N'BANCO DE GUAYAQUIL,S.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E017', N'BANCO DEL ESTADO DE CHILE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E018', N'BANCO DO BRASIL', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E019', N'BANCO ESPAÑOL DE CREDITO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E020', N'BANCO FINANCIERO DEL PERU', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E021', N'BANCO GENERAL', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E022', N'BANCO INTERNACIONAL DE COSTA RICA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E023', N'BANCO LAFISE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E024', N'BANCO PICHINCHA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E025', N'BANCO SABADELL', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E026', N'BANCO SANTANDER CENTRAL HISPANO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E027', N'BANCO UNIVERSAL TRUST CORPORATION', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E029', N'BANCOLOMBIA', N'Exter')
GO
print 'Processed 100 total records'
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E030', N'BANK FOR INTERNATIONAL SETTLEMENTS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E031', N'BANK HAPOALIM', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E032', N'BANK LEUMI', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E033', N'BANK OF AMERICA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E034', N'BANK OF CHINA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E035', N'BARCLAYS BANK P.L.C.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E036', N'BAYERISCHE HYPO UND VEREINSBANK AG', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E037', N'BCG GUATEMALA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E038', N'BCH HONDURAS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E039', N'BEAR STEARNS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E040', N'BNP PARIBAS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E041', N'CAJA DE AHORROS DE GALICIA (CAIXA GALICIA)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E042', N'CITIBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E043', N'CLEARSTREAM BANKING', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E044', N'COBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E045', N'COMMERZBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E046', N'CORPORACION ANDINA DE FOMENTO (CAF)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E047', N'CREDIT AGRICOLE S.A. (CALYON)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E048', N'CREDIT SUISSE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E049', N'CHARLES SCHWAB', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E050', N'DANSKE BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E051', N'DEPFA BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E052', N'DEUTSCHE BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E053', N'DEXIA BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E054', N'DNB NOR BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E055', N'DRESDNER BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E057', N'EFG BANK & TRUST', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E058', N'FEDERAL RESERVE BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E061', N'FORTIS BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E062', N'GLOBAL BANK OVERSEAS LIMITED', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E063', N'GOLDMAN SACHS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E064', N'HSBC GROUP', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E065', N'ING BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E066', N'INTERNATIONAL BANK OF MIAMI', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E067', N'INTESA SANPAOLO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E068', N'ISRAEL DISCOUNT BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E069', N'JP MORGAN CHASE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E070', N'KBC BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E071', N'KOREA EXCHANGE BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E072', N'LEHMAN BROTHERS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E073', N'LLOYDS TSB BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E074', N'MEGA INTERNATIONAL COMMERCIAL BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E075', N'MERCANTIL, C. A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E076', N'MERRILL LYNCH', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E077', N'MIZUHO CORPORATE BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E078', N'MORGAN STANLEY', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E079', N'NATIONAL WESTMINSTER BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E080', N'NATIXIS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E083', N'RABOBANK INTERNATIONAL', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E084', N'RBS COUTTS BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E085', N'SAFRA NATIONAL BANK N.Y.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E086', N'SKANDINAVISKA ENSKILDA BANKEN', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E087', N'SMITH BARNEY', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E088', N'SOCIETE GENERALE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E089', N'STANDARD CHARTERED BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E090', N'SUMITOMO MITSUI BANKING', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E091', N'SVENSKA HANDELSBANKEN', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E092', N'SWEDBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E093', N'THE BANK OF MONTREAL', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E094', N'THE BANK OF NEW YORK MELLON', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E096', N'THE BANK OF NOVA SCOTIA (SCOTIABANK)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E097', N'THE BANK OF TOKYO MITSUBISHI', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E098', N'THE ROYAL BANK OF CANADA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E099', N'THE ROYAL BANK OF SCOTLAND', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E100', N'TOWERBANK LTD', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E101', N'UBS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E102', N'UNICREDITO ITALIANO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E103', N'WACHOVIA BANK, N. A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E104', N'WELLS FARGO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E105', N'WESTDEUTSCHE LANDESBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E106', N'BANCO POPULAR DOMINICANO  ', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E107', N'BANK OF IRELAND', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E108', N'CREDIT LYONNAIS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E109', N'CANADIAN IMPERIAL BANK OF COMMERCE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E110', N'NATIONAL BANK OF CANADA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E111', N'NORDEA BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E112', N'PNC BANK N.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E116', N'REGIONS BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E117', N'RZB BANK RAIFFEISEN ZENTRALBANK ÖSTERREICH AG (RZB)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E118', N'TORONTO DOMINION BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E120', N'BANCO DE CRÉDITO CENTROAMERICANO (BANCENTRO)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E121', N'BANCO DE CRÉDITO HFS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E123', N'BANCO NACIONAL DE MÉXICO, S.A. (BANAMEX)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E124', N'BBU BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E125', N'BANESCO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E126', N'BANCO CENTRAL DE COSTA RICA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E127', N'US CENTURY BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E128', N'PRUDENTIAL SECURITIES  BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E129', N'BANQUE FRANCK, GALLAND & CIE S.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E130', N'UNION BANCAIRE PRIVÉE (UBP).', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E131', N'BANK OF SCOTLAND PLC', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E132', N'KOREA DEVELOPMENT BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E133', N'ZURCHER KANTONALBANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E134', N'MMG BANK & TRUST LTD.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E135', N'ANZ NATIONAL BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E136', N'BANCO DE LA NACIÓN ARGENTINA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E137', N'LANDESBANK BADEN-WÜRTTEMBERG', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E138', N'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E139', N'BANCO PROMERICA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E140', N'AB BANK SNORAS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E141', N'EASTERN NATIONAL BANK', N'Exter')
GO
print 'Processed 200 total records'
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E142', N'BANCO DE COSTA RICA, S. A', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E143', N'BCT BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E144', N'BANCO DEL PACIFICO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E145', N'SOCIETE FINANCIERE DES ANTILLES', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E147', N'BANCO DE BOGOTA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E148', N'BANK OF ANTIGUA ', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E149', N'BANCO BHD ', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E150', N'BANCO DE COMERCIO EXTERIOR DE COLOMBIA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E151', N'BANCO DE OCCIDENTE', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E152', N'BANCO G&T CONTINENTAL, S.A.', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E153', N'BANCO INDUSTRIAL DE GUATEMALA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E154', N'BANCO AGRÍCOLA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E155', N'CREDIT ANDORRA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E156', N'BANCO BOLIVARIANO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E157', N'BANCO AMAZONAS', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E158', N'PRODUBANCO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E159', N'BANKATLANTIC', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E160', N'INDUSTRIAL BANK OF KOREA', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E161', N'GNB SUDAMERIS BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E162', N'ATLANTIC SECURITY BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E163', N'BUTTERFIELD BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E164', N'BANCO ITAU  ', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E165', N'BRADESCO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E166', N'BANCO DE LA PROVINCIA DE BUENOS AIRES', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E167', N'US BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E168', N'MODERN BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E169', N'DAVOS INTERNATIONAL BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E170', N'BANCO ESPIRITO SANTO', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E171', N'BANCO INTERNACIONAL DEL PERÚ', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E172', N'GRUPO BANCARIO IF', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E173', N'BANCO POPULAR, S.A. (COLOMBIA)', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E174', N'FIRSTCARIBBEAN INTERNATIONAL BANK', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E175', N'BANCO GENERAL RUMIÑAHUI', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E176', N'BANCO DE CREDITO DEL PERU', N'Exter')
INSERT [dbo].[Bancos] ([ID], [Nombre], [Categoria]) VALUES (N'E999', N'OTRAS ENTIDADES BANCARIAS', N'Exter')
