-- =============================================
-- Script Template
-- =============================================


--SB58

INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'NA', N'NA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'701', N'ACAPI, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'702', N'AIR AVALUOS 390')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'703', N'APA VENTAS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'704', N'ASETECNIA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'705', N'ASETECNIA, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'706', N'AVAISTMO')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'707', N'AVALUOS E INSPECCIONES, S A (AISA)')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'708', N'AVALUOS INSPECCIONES Y CONSTRUCCIONES')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'709', N'AVANCE INSPECCIONES')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'710', N'B & L COMMERCIAL VALUE INC')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'711', N'BIENES RAICES SATELITE')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'712', N'BIENES RAÍCES Y SEGUROS CARLES')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'713', N'BRYC''S PRINCIPAL, INC 15960')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'714', N'CB RICHARD ELLIS 780')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'715', N'CETSA, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'716', N'CIMA AVALUOS Y ARQUITECTURA, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'717', N'COMIVENSA, S A-AVALÚOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'718', N'COMPAÑÍA HERMES CARRIZO')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'719', N'COMPAÑÍA NACIONAL DE AVALÚOS, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'720', N'CONSTRUCCIONES Y SERVICIOS M & C')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'721', N'CONSTRUCTORA DOMAR, S.A.')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'722', N'CORPORACION DE INGENIEROS ASOCIADOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'723', N'EVALUACION DE PROYECTOS DE INVERSION')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'724', N'GEO PANAMÁ I S, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'725', N'IACOSA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'726', N'IBS AVALÚOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'727', N'ICAPSA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'728', N'IN SITU INSPECTORS, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'729', N'INGENIERIA HORIZONTE')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'730', N'INTERNATIONAL CAR CENTER')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'731', N'INVERSIONES DIMSA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'732', N'INVERSIONES NATASHA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'733', N'INVERSIONES PANAMA FLORIDA')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'734', N'LUIS MUÑOZ, S.A.')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'735', N'LYM CONSTRUCTIONS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'736', N'MALLOL & MALLOL AVALUOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'737', N'MAYHOUSE, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'738', N'METAMORFOSIS ARQUITECTOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'739', N'PANAMÁ SURVEYORS BUREAU INC')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'740', N'PANAMERICANA DE AVALUOS, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'741', N'PATEL AUTOS 390')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'742', N'Q.C. & STANDARD CONSTRUCTION')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'743', N'ROMERO REALTY, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'744', N'SUDAMERICANA DE AVALÚOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'745', N'TINKER TINKER AVALUOS')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'746', N'TOYOMOVILSA, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'747', N'TRÁMITES TRIBUTARIOS, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'748', N'VALUACIONES INMOBILIARIAS, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'749', N'ZUBIETA Y ZUBIETA, S A')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'750', N'Asmar Inc')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'788', N'Persona Natural')
INSERT [dbo].[Avaluadoras] ([ID], [Nombre]) VALUES (N'799', N'Avaluadora en el Exterior')
