-- =============================================
-- Script Template
-- =============================================

--Tabla paises BLX + SB03

INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'N/A', N'NA', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AD', N'ANDORRA', N'020')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AE', N'UNITED ARAB EMIRATES', N'784')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AF', N'AFGHANISTAN', N'004')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AG', N'ANTIGUA AND BARBUDA', N'028')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AI', N'ANGUILLA', N'660')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AL', N'ALBANIA', N'008')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AM', N'ARMENIA', N'051')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AN', N'NETHERLANDS ANTILLES', N'530')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AO', N'ANGOLA', N'024')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AQ', N'ANTARCTICA', N'010')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AR', N'ARGENTINA', N'032')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AS', N'AMERICAN SAMOA', N'016')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AT', N'AUSTRIA', N'040')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AU', N'AUSTRALIA', N'036')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AW', N'ARUBA', N'533')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'AZ', N'AZERBAIJAN', N'031')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BA', N'BOSNIA AND HERZEGOWINA', N'070')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BB', N'BARBADOS', N'052')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BD', N'BANGLADESH', N'050')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BE', N'BELGIUM', N'056')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BF', N'BURKINA FASO', N'854')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BG', N'BULGARIA', N'100')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BH', N'BAHRAIN', N'048')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BI', N'BURUNDI', N'108')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BJ', N'BENIN', N'204')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BM', N'BERMUDA', N'060')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BN', N'BRUNEI DARUSSALAM', N'096')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BO', N'BOLIVIA', N'068')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BR', N'BRAZIL', N'076')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BS', N'BAHAMAS', N'044')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BT', N'BHUTAN', N'064')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BV', N'BOUVET ISLAND', N'074')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BW', N'BOTSWANA', N'072')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BY', N'BELARUS', N'112')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'BZ', N'BELIZE', N'084')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CA', N'CANADA', N'124')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CC', N'COCOS (KEELING) ISLANDS', N'166')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CD', N'CONGO, DEMOCRATIC REPUBLIC OF', N'180')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CF', N'CENTRAL AFRICAN REPUBLIC', N'140')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CG', N'CONGO, PEOPLE''S REPUBLIC OF', N'178')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CH', N'SWITZERLAND', N'756')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CI', N'COTE D''IVOIRE', N'384')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CK', N'COOK ISLANDS', N'184')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CL', N'CHILE', N'152')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CM', N'CAMEROON', N'120')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CN', N'CHINA', N'156')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CO', N'COLOMBIA', N'170')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CR', N'COSTA RICA', N'188')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CU', N'CUBA', N'192')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CV', N'CAPE VERDE', N'132')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CX', N'CHRISTMAS ISLAND', N'162')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CY', N'CYPRUS', N'196')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'CZ', N'CZECH REPUBLIC', N'203')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DE', N'GERMANY', N'276')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DJ', N'DJIBOUTI', N'262')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DK', N'DENMARK', N'208')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DM', N'DOMINICA', N'212')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DO', N'DOMINICAN REPUBLIC', N'214')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'DZ', N'ALGERIA', N'012')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'EC', N'ECUADOR', N'218')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'EE', N'ESTONIA', N'233')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'EG', N'EGYPT', N'818')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'EH', N'WESTERN SAHARA', N'732')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ER', N'ERITREA', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ES', N'SPAIN', N'724')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ET', N'ETHIOPIA', N'231')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'EU', N'EUROPEAN UNION', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FI', N'FINLAND', N'246')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FJ', N'FIJI', N'242')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FK', N'FALKLAND ISLANDS (MALVINAS)', N'238')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FM', N'MICRONESIA, FEDERATED STATES OF', N'583')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FO', N'FAROE ISLANDS', N'234')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FR', N'FRANCE', N'250')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'FX', N'FRANCE, METROPOLITAN', N'249')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GA', N'GABON', N'266')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GB', N'UNITED KINGDOM', N'826')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GD', N'GRENADA', N'308')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GE', N'GEORGIA', N'268')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GF', N'FRENCH GUIANA', N'254')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GH', N'GHANA', N'288')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GI', N'GIBRALTAR', N'292')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GL', N'GREENLAND', N'304')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GM', N'GAMBIA', N'270')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GN', N'GUINEA', N'324')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GP', N'GUADELOUPE', N'312')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GQ', N'EQUATORIAL GUINEA', N'226')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GR', N'GREECE', N'300')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GS', N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', N'239')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GT', N'GUATEMALA', N'320')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GU', N'GUAM', N'316')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GW', N'GUINEA-BISSAU', N'624')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'GY', N'GUYANA', N'328')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HK', N'HONG KONG', N'344')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HM', N'HEARD AND MC DONALD ISLANDS', N'334')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HN', N'HONDURAS', N'340')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HR', N'CROATIA (LOCAL NAME: HRVATSKA)', N'191')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HT', N'HAITI', N'332')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'HU', N'HUNGARY', N'348')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ID', N'INDONESIA', N'360')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IE', N'IRELAND', N'372')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IL', N'ISRAEL', N'376')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IN', N'INDIA', N'356')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IO', N'BRITISH INDIAN OCEAN TERRITORY', N'086')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IQ', N'IRAQ', N'368')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IR', N'IRAN (ISLAMIC REPUBLIC OF)', N'364')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IS', N'ICELAND', N'352')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'IT', N'ITALY', N'380')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'JM', N'JAMAICA', N'388')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'JO', N'JORDAN', N'400')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'JP', N'JAPAN', N'392')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KE', N'KENYA', N'404')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KG', N'KYRGYZSTAN', N'417')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KH', N'CAMBODIA', N'116')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KI', N'KIRIBATI', N'296')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KM', N'COMOROS', N'174')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KN', N'SAINT KITTS AND NEVIS', N'659')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KP', N'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KR', N'KOREA, REPUBLIC OF', N'410')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KW', N'KUWAIT', N'414')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KY', N'CAYMAN ISLANDS', N'136')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'KZ', N'KAZAKHSTAN', N'398')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LA', N'LAO PEOPLE''S DEMOCRATIC REPUBLIC', N'418')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LB', N'LEBANON', N'422')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LC', N'SAINT LUCIA', N'662')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LI', N'LIECHTENSTEIN', N'438')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LK', N'SRI LANKA', N'144')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LR', N'LIBERIA', N'430')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LS', N'LESOTHO', N'426')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LT', N'LITHUANIA', N'440')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LU', N'LUXEMBOURG', N'442')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LV', N'LATVIA', N'428')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'LY', N'LIBYAN ARAB JAMAHIRIYA', N'434')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MA', N'MOROCCO', N'504')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MC', N'MONACO', N'492')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MD', N'MOLDOVA, REPUBLIC OF', N'498')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MG', N'MADAGASCAR', N'450')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MH', N'MARSHALL ISLANDS', N'584')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MI', N'MULTINATIONAL', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MK', N'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', N'807')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ML', N'MALI', N'466')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MM', N'MYANMAR', N'104')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MN', N'MONGOLIA', N'496')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MO', N'MACAU', N'446')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MP', N'NORTHERN MARIANA ISLANDS', N'580')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MQ', N'MARTINIQUE', N'474')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MR', N'MAURITANIA', N'478')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MS', N'MONTSERRAT', N'500')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MT', N'MALTA', N'470')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MU', N'MAURITIUS', N'480')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MV', N'MALDIVES', N'462')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MW', N'MALAWI', N'454')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MX', N'MEXICO', N'484')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MY', N'MALAYSIA', N'458')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'MZ', N'MOZAMBIQUE', N'508')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NA', N'NAMIBIA', N'516')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NC', N'NEW CALEDONIA', N'540')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NE', N'NIGER', N'562')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NF', N'NORFOLK ISLAND', N'574')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NG', N'NIGERIA', N'566')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NI', N'NICARAGUA', N'558')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NL', N'NETHERLANDS', N'528')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NO', N'NORWAY', N'578')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NP', N'NEPAL', N'524')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NR', N'NAURU', N'520')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NU', N'NIUE', N'570')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'NZ', N'NEW ZEALAND', N'554')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'OM', N'OMAN', N'512')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PA', N'PANAMA', N'591')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PE', N'PERU', N'604')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PF', N'FRENCH POLYNESIA', N'258')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PG', N'PAPUA NEW GUINEA', N'598')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PH', N'PHILIPPINES', N'608')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PK', N'PAKISTAN', N'586')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PL', N'POLAND', N'616')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PM', N'ST. PIERRE AND MIQUELON', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PN', N'PITCAIRN', N'612')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PR', N'PUERTO RICO', N'630')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PS', N'PALESTINIAN TERRITORY, OCCUPIED', N'275')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PT', N'PORTUGAL', N'620')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PW', N'PALAU', N'585')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'PY', N'PARAGUAY', N'600')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'QA', N'QATAR', N'634')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'RE', N'REUNION', N'638')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'RO', N'ROMANIA', N'642')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'RU', N'RUSSIAN FEDERATION', N'643')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'RW', N'RWANDA', N'646')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SA', N'SAUDI ARABIA', N'682')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SB', N'SOLOMON ISLANDS', N'090')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SC', N'SEYCHELLES', N'690')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SD', N'SUDAN', N'736')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SE', N'SWEDEN', N'752')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SG', N'SINGAPORE', N'702')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SH', N'ST. HELENA', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SI', N'SLOVENIA', N'705')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SJ', N'SVALBARD AND JAN MAYEN ISLANDS', N'744')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SK', N'SLOVAKIA (SLOVAK REPUBLIC)', N'703')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SL', N'SIERRA LEONE', N'694')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SM', N'SAN MARINO', N'674')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SN', N'SENEGAL', N'686')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SO', N'SOMALIA', N'706')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SR', N'SURINAME', N'740')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ST', N'SAO TOME AND PRINCIPE', N'678')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SV', N'EL SALVADOR', N'222')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SY', N'SYRIAN ARAB REPUBLIC', N'760')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'SZ', N'SWAZILAND', N'748')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TC', N'TURKS AND CAICOS ISLANDS', N'796')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TD', N'CHAD', N'148')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TF', N'FRENCH SOUTHERN TERRITORIES', N'260')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TG', N'TOGO', N'768')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TH', N'THAILAND', N'764')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TJ', N'TAJIKISTAN', N'762')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TK', N'TOKELAU', N'772')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TL', N'EAST TIMOR', N'626')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TM', N'TURKMENISTAN', N'795')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TN', N'TUNISIA', N'788')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TO', N'TONGA', N'776')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TR', N'TURKEY', N'792')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TT', N'TRINIDAD AND TOBAGO', N'780')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TV', N'TUVALU', N'798')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TW', N'TAIWAN', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'TZ', N'TANZANIA, UNITED REPUBLIC OF', N'834')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'UA', N'UKRAINE', N'804')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'UG', N'UGANDA', N'800')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'UM', N'UNITED STATES MINOR OUTLYING ISLANDS', N'581')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'US', N'UNITED STATES', N'840')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'UY', N'URUGUAY', N'858')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'UZ', N'UZBEKISTAN', N'860')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VA', N'VATICAN CITY STATE (HOLY SEE)', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VAR', N'VARIOS VER DESGLOSE', N'')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VC', N'SAINT VINCENT AND THE GRENADINES', N'670')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VE', N'VENEZUELA', N'862')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VG', N'VIRGIN ISLANDS (BRITISH)', N'092')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VI', N'VIRGIN ISLANDS (U.S.)', N'850')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VN', N'VIET NAM', N'704')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'VU', N'VANUATU', N'548')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'WF', N'WALLIS AND FUTUNA ISLANDS', N'876')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'WS', N'SAMOA', N'882')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'YE', N'YEMEN', N'887')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'YT', N'MAYOTTE', N'175')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'YU', N'YUGOSLAVIA', N'891')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ZA', N'SOUTH AFRICA', N'710')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ZM', N'ZAMBIA', N'894')
INSERT [dbo].[Pais] ([ID], [Nombre], [CodigoSuper]) VALUES (N'ZW', N'ZIMBABWE', N'716')
