//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Entidad que representa los actores en el modelo. 
    /// Los actores representan un nombre y un pais relacionados.
    /// Modela una tupla de Nombre y Pais
    /// </summary>
    public class Actor : EntityBase
    {
	
        /// <summary>
        /// Nombre del Actor.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// <see cref="Pais"/>
        /// </summary>
        public virtual Pais Pais
        {
            get;
            set;
        }

    }
}

