//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa Avales pertenecientes a <see cref="GarantiaOtra"/>
    /// </summary>
    public class Aval : EntityBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Aval"/> class.
        /// </summary>
        public Aval()
        {
            this.Pais = new Pais();
            this.TipoAval = new TipoAval();
        }

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the porcentaje cobertura.
        /// </summary>
        /// <value>
        /// The porcentaje cobertura.
        /// </value>
        public virtual double PorcentajeCobertura
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the pais.
        /// </summary>
        /// <value>
        /// The pais.
        /// </value>
        public virtual Pais Pais
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets a value indicating whether [es cliente].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [es cliente]; otherwise, <c>false</c>.
        /// </value>
        public virtual Boolean EsCliente
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the tipo aval.
        /// </summary>
        /// <value>
        /// The tipo aval.
        /// </value>
        public virtual TipoAval TipoAval
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the garantia id.
        /// </summary>
        /// <value>
        /// The garantia id.
        /// </value>
        public virtual int GarantiaId
        {
            get;
            set;
        }

    }
}

