//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Clase Avaluadoras que representa un catalogo de la super. 
    /// Tabla SB58
    /// </summary>
    /// <remarks>
    /// SB58
    /// </remarks>
    public class Avaluadoras : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre of type <see cref="System.String"/>
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

    }
}

