//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa un Banco. 
    /// Entidad proveniente de catalogos de la super.
    /// Catalogos: SB01 (Categoria=Local) y SB39 (Cateogria=Externo)
    /// </summary>
    /// <remarks>
    /// SB01 (Categoria=Local) y SB39 (Cateogria=Externo)
    /// </remarks>
    public class Bancos : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Local | Extranjero 
        /// </summary>
        public virtual string Categoria
        {
            get;
            set;
        }

    }
}

