//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa la calificacion de riesgo de una garantia.
    /// </summary>
    public class CalificacionesRiesgo : EntityBase
    {

        /// <summary>
        /// Gets or sets the orden.
        /// </summary>
        /// <value>
        /// The orden.
        /// </value>
        public virtual int Orden
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the moodys.
        /// </summary>
        /// <value>
        /// The moodys.
        /// </value>
        public virtual string Moodys
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the fitch.
        /// </summary>
        /// <value>
        /// The fitch.
        /// </value>
        public virtual string Fitch
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the sn P.
        /// </summary>
        /// <value>
        /// The sn P.
        /// </value>
        public virtual string SnP
        {
            get;
            set;
        }

        /// <summary>
        /// Returns a <see cref="System.String"/> that represents this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="System.String"/> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            if (this.GetKeyAs<string>().ToUpper() == "NA")
                return "NA";
            else
                return string.Format("{0} - Moodys: {1}, Fitch: {2}, Snp: {3}", Orden, Moodys, Fitch, SnP);
        }

    }
}

