//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa la categoria de riesgo de una garantía.
    /// </summary>
    public class CategoriaRiesgoGarantia : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the grupo.
        /// </summary>
        /// <value>
        /// The grupo. <see cref="GrupoRiesgoGarantia"/>
        /// </value>
        public virtual GrupoRiesgoGarantia Grupo
        {
            get;
            set;
        }

       

    }
}

