//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.DomainModel.Repositories;
using Bladex.Garantias.DomainModel.Services;
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Categoria Super:
    /// 01	Garantía Hipotecaria Mueble
    /// 02	Garantía Hipotecaria Inmueble
    /// 03	Depósitos Pignorados en el Banco
    /// 04	Depósitos Pignorados en Otros Bancos
    /// 05	Garantía Prendaria
    /// 06	Otras Garantías
    /// </summary>
    /// <remarks>
    /// Categoria Super:
    /// 01	Garantía Hipotecaria Mueble
    /// 02	Garantía Hipotecaria Inmueble
    /// 03	Depósitos Pignorados en el Banco
    /// 04	Depósitos Pignorados en Otros Bancos
    /// 05	Garantía Prendaria
    /// 06	Otras Garantías
    /// </remarks>
    public class CategoriaSuper : EntityBase
    {
        /// <summary>
        ///   Garantia Mueble - 01
        /// </summary>
        public const string MUEBLE_ID = "01";
        /// <summary>
        ///   Garantia Inmueble - 02
        /// </summary>
        public const string INMUEBLE_ID = "02";
        /// <summary>
        ///   Garantia Deposito - 03
        /// </summary>
        public const string DEPOSITO_ID = "03";
        /// <summary>
        ///   Garantia Deposito Otros Bancos - 04
        /// </summary>
        public const string DEPOSITO_OTROS_ID = "04";
        /// <summary>
        ///   Garantia Prendaria - 05
        /// </summary>
        public const string PRENDARIA_ID = "05";
        /// <summary>
        ///   Garantia Otras - 06
        /// </summary>
        public const string OTRAS_ID = "06";

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is read only.
        /// </summary>
        /// <value>
        /// 	<c>true</c> if this instance is read only; otherwise, <c>false</c>.
        /// </value>
        public bool IsReadOnly
        {
            get;
            set;
        }

    }
}

