//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Bladex.Garantias.Infrastructure.DomainBase;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Clase encargada de representar un cliente proveniente de Carga Historica.
    /// </summary>
    public class Cliente : EntityBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cliente"/> class.
        /// </summary>
        public Cliente()
        {
            this.IsInternal = false;
        }

        /// <summary>
        /// Nombre del cliente
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Rating de riesgo
        /// </summary>
        public virtual string Rating
        {
            get;
            set;
        }

        /// <summary>
        /// Grupo Economico
        /// </summary>
        public virtual string GrupoEconomico
        {
            get;
            set;
        }

        /// <summary>
        /// Codigo del pais
        /// </summary>
        public virtual Pais Pais
        {
            get;
            set;
        }

        /// <summary>
        /// NationalId de Carga Historica. Mapea con RUC_CODE
        /// </summary>
        public string NationalId
        {
            get;
            set;
        }

        /// <summary>
        /// Business_Line_Desc_2 from FCC.
        /// </summary>
        public string BusinessLineDescription
        {get;set;}

        public string AccountOfficer
        {
            get;set;
        }

        /// <summary>
        /// AccountOfficer field from FCC
        /// </summary>
        public string GlobalLineDescription
        {
            get;set;
        }

        public string AuthStat
        { get; set; }
        
        public string RecordStat
        { get; set; }
        
        public string LimitExpDate
        { get; set; }

        public bool? IsActive
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is internal.
        /// </summary>
        /// <value>
        /// 	<c>true</c> if this instance is internal; otherwise, <c>false</c>.
        /// </value>
        public bool IsInternal
        { get; set; }

        /// <summary>
        /// Property used to decide if the customer is guarantor or if not.
        /// </summary>
        public bool IsGarante
        {
            get 
            {
                if (string.IsNullOrEmpty(LimitExpDate))
                    return false;
                else if (LimitExpDate == "19800101")
                    return true;
                else if (LimitExpDate == "19700101")
                    return false;
                else
                    return false;
            }
        }



    }

}