//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Clase encargada de representar una frecuencia de tiempo.
    /// Se utiliza para calcular el campo Next Review Date en base a la <see cref="Frecuencias"/> especificada
    /// </summary>
    public class Frecuencias : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }


        /// <summary>
        /// Gets or sets the unidad.
        /// </summary>
        /// <value>
        /// The unidad of type <see cref="Bladex.Garantias.DomainModel.DomainBase.UnidadFrecuenciaEnum"/>
        /// </value>
        public virtual UnidadFrecuenciaEnum? Unidad
        { get; set; }


        /// <summary>
        /// Gets or sets the valor frecuencia.
        /// </summary>
        /// <value>
        /// The valor frecuencia of type <see cref="System.Int32"/>
        /// </value>
        public virtual int ValorFrecuencia { get; set; }

    }
}

