//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Bladex.Garantias.DomainModel.Services;
using Bladex.Garantias.DomainModel.DomainBase.Components.AvalManager;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa Garantía del tipo Otras.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaOtra : GarantiaBase
    {
        public GarantiaOtra():base()
        {
            //CategoriaSuperService srv = new CategoriaSuperService();
            //this.CategoriaSuper = srv.GetById(CategoriaSuper.OTRAS_ID);
            this.Avales = new List<Aval>();
            //this.Emisor = new ActorService().GetEmpty();
        }

        /// <summary>
        /// Listado de Avales de la Garantia. Aplica para "0604 - Fianzas y Avales Bancarios" y " 0605 - Fianzas y Avales No Bancarios".
        /// </summary>
        public virtual List<Aval> Avales { 
            get; 
            set; 
        }


        public virtual Actor Emisor
        {
            get;
            set;
        }


        public virtual AvalManager AvalComponent
        {
            get;
            set;
        }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        public virtual string NroReferencia
        {
            get;
            set;
        }

        #region Old GetNombreOrganismo code
        //public override string GetNombreOrganismo()
        //{
        //    if (this.TipoGarantiaSuper != null && this.TipoGarantiaSuper.Key != null && (this.TipoGarantiaSuper.GetKeyAs<string>() == "0604" || this.TipoGarantiaSuper.GetKeyAs<string>() == "0605"))
        //    {
        //        if (this.Garante == null) 
        //            return string.Empty;
                
        //        if (this.Garante.IsDirty)
        //        {
        //            if (this.Garante.Key == null) 
        //                return string.Empty;
                    
        //            this.SetNombreOrganismo(this.Garante.GetKeyAs<string>());
        //        }
        //        return string.IsNullOrEmpty(this.Garante.Nombre) ? string.Empty : this.Garante.Nombre;
        //    }
        //    else
        //    {
        //        if (this.Emisor == null) return string.Empty;
        //        if (this.Emisor.IsDirty)
        //        {
        //            if (this.Emisor.Key == null) return string.Empty;
        //            this.SetNombreOrganismo(this.Emisor.Nombre);
        //        }
        //        return this.Emisor.Nombre;
        //    }
        //}

        ///// <summary>
        ///// Setea el nombre del organismo. Para Tipos 0605 y 0604 se espera un garante, para otros tipos un Emisor.
        ///// </summary>
        ///// <param name="valor">Para tipos 0605 y 0604 se espera un Garante.Key, para otros se espera un Emisor.Nombre</param>
        //public override void SetNombreOrganismo(string valor)
        //{
        //    if (!string.IsNullOrEmpty(valor))
        //    {
        //        if (this.TipoGarantiaSuper != null && this.TipoGarantiaSuper.Key != null && (this.TipoGarantiaSuper.GetKeyAs<string>() == "0604" || this.TipoGarantiaSuper.GetKeyAs<string>() == "0605"))
        //        {
        //            ClienteService srv = new ClienteService();
        //            this.Garante = srv.GetById(valor);
        //        }
        //        else
        //        {
        //            ActorService srv = new ActorService();
        //            this.Emisor = srv.GetByName(valor);
        //        }
        //    }
        //}
        #endregion

        public override string GetIdentificacionDocumentoGarantia()
        {
            //return this.NroIncidenteWorkflow;
            //return this.FCCReference;
            if (this.NroReferencia == null || string.IsNullOrEmpty(this.NroReferencia) || this.NroReferencia.ToUpper() == "NA")
            {
                if (this.Key!=null && !string.IsNullOrEmpty(this.Key.ToString()))
                    return this.Key.ToString();
                else
                    return "NA";
            }
            else
            {
                return this.NroReferencia;
            }

        }
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            //this.NroIncidenteWorkflow = valor;
            //this.FCCReference = valor;
            this.NroReferencia = valor;
        }
        
        /// <summary>
        ///  (buscar linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial")
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorMercado != null & this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;
        }
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorMercado = valor;
        }
    }
}

