//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bladex.Garantias.DomainModel.Services;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa una Garantía del tipo Inmueble.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaInmueble : GarantiaBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaInmueble"/> class.
        /// </summary>
        public GarantiaInmueble() :base()
        {
            //CategoriaSuperService srv = new CategoriaSuperService();
            //this.CategoriaSuper = srv.GetById(CategoriaSuper.INMUEBLE_ID);
        }

        /// <summary>
        /// (Distressed Sale Value)
        /// </summary>
        public virtual Decimal ValorEvaluacionVentaRapida
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha Inicial del Avaluo
        /// </summary>
        public DateTime? FechaInicialAvaluo
            { get; set; }

        /// <summary>
        /// Fecha Vencimiento Avaluo
        /// </summary>
        public DateTime? FechaVencimientoAvaluo
            { get; set; }

        /// <summary>
        /// Valor Total Avaluo
        /// </summary>
        public decimal ValorTotalAvaluo
            { get; set; }

        /// <summary>
        /// Valor de Avaluo
        /// </summary>
        public Decimal ValorAvaluo
        {
            get;
            set;
        }

        /// <summary>
        /// Inscripcion Registro Publico
        /// </summary>
        public virtual string InscripcionRegistroPublico
        {
            get;
            set;
        }

        /// <summary>
        /// Numero de Finca
        /// </summary>
        public virtual string NumeroDeFinca
        {
            get;
            set;
        }


        /// <summary>
        /// Mueble
        /// Código que identifica el Nombre de la Aseguradora según la tabla SB57  
        /// (Aseguradoras)
        /// 
        /// Inmueble
        /// Código que identifica el Nombre del avaluador de la Finca según la tabla SB58 
        /// (Avaluadoras)
        /// 
        /// Resto:
        /// N/A
        /// </summary>
        public virtual Avaluadoras AseguradorSuper
        {
            get;
            set;
        }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        #region Old GetNombreOrganismo code

        //public override string GetNombreOrganismo()
        //{
        //    if (this.AseguradorSuper == null) return string.Empty;
        //    if (this.AseguradorSuper.IsDirty && this.AseguradorSuper.Key != null)
        //    {
        //        this.SetNombreOrganismo(this.AseguradorSuper.Key.ToString());
        //    }
        //    // Reemplazo linea, originalmente se retornaba el Key, cambia por el nombre.
        //    return (this.AseguradorSuper != null && !string.IsNullOrEmpty(this.AseguradorSuper.Nombre)) ? this.AseguradorSuper.Nombre.ToString() : string.Empty;
        //}
        //public override void SetNombreOrganismo(string valor)
        //{
        //    AvaluadoraService srv = new AvaluadoraService();
        //    this.AseguradorSuper = srv.GetById(valor);
        //    if (this.AseguradorSuper == null)
        //    {
        //        this.AseguradorSuper = AvaluadoraService.GetEmpty();
        //    }
        //}

        #endregion

        public override string GetIdentificacionDocumentoGarantia()
        {
            if (string.IsNullOrEmpty(this.InscripcionRegistroPublico) && string.IsNullOrEmpty(this.NumeroDeFinca))
                return string.Empty;

            return string.Format("{0}/{1}", this.InscripcionRegistroPublico, this.NumeroDeFinca);
        }
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            string[] result = valor.Split('/');
            if (result.Length == 2)
            {
                this.InscripcionRegistroPublico = result[0];
                this.NumeroDeFinca = result[1];
            }
            else
            {
                this.InscripcionRegistroPublico = valor;
            }
        }

        /// <summary>
        /// (buscar linea 56 "Valor Evaluación Venta Rápida / Distressed Sale Value", em su falta linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial" )
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorAvaluo != null && this.ValorAvaluo != 0)
            {
                return this.ValorAvaluo;
            }
            else if (this.ValorEvaluacionVentaRapida != null && this.ValorEvaluacionVentaRapida != 0)
            {
                return this.ValorEvaluacionVentaRapida;
            }
            else if (this.ValorMercado != null && this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;
        }
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorAvaluo = valor;
        }

        /// <summary>
        ///  Distressed Sale Value (En caso de no especificarse utiliza el ValorMercado y en su defecto el el ValorInicial) / ValorNecesario
        /// </summary>
        /// <returns></returns>
        public override Double GetRatioCoberturaGarantia()
        {
            if (this.ValorNecesarioDeGarantia == 0)
                return 0;

            if ( this.ValorEvaluacionVentaRapida != 0)
            {
                return (double) this.ValorEvaluacionVentaRapida / (double) this.ValorNecesarioDeGarantia;
            }
            else 
            if (this.ValorMercado != 0)
            {
                return (double)this.ValorMercado / (double)this.ValorNecesarioDeGarantia;
            }

            return (double)this.ValorInicial / (double)this.ValorNecesarioDeGarantia;

        }
    }
}

