//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Bladex.Garantias.DomainModel.Services;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa una Garantía Deposito.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaDeposito : GarantiaBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaDeposito"/> class.
        /// </summary>
        public GarantiaDeposito():base()
        {
            //CategoriaSuperService srv = new CategoriaSuperService();
            //this.CategoriaSuper = srv.GetById(CategoriaSuper.DEPOSITO_ID);
        }

        /// <summary>
        /// Restriccion Bancos.Categoria=Local
        /// </summary>
        public virtual Bancos BancoLocalSuper
        {
            get;
            set;
        }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        #region Old GetNombreOrganismo code

        ///// <summary>
        ///// Gets the nombre organismo.
        ///// </summary>
        ///// <returns></returns>
        //public override string GetNombreOrganismo()
        //{
        //    if (this.BancoLocalSuper == null) return string.Empty;
        //    if (this.BancoLocalSuper.IsDirty && this.BancoLocalSuper.Key != null)
        //    {
        //        this.SetNombreOrganismo(this.BancoLocalSuper.Key.ToString());
        //    }
        //    // Reemplazo linea, originalmente se retornaba el Key, cambia por el nombre.
        //    return !string.IsNullOrEmpty(this.BancoLocalSuper.Nombre) ? this.BancoLocalSuper.Nombre.ToString() : string.Empty;
        //}
        ///// <summary>
        ///// Sets the nombre organismo.
        ///// </summary>
        ///// <param name="valor">The valor.</param>
        //public override void SetNombreOrganismo(string valor)
        //{
        //    if (string.IsNullOrEmpty(valor)) return;
        //    //TODO: Revisar si es correcto
        //    BancosService srv = new BancosService();
        //    this.BancoLocalSuper = srv.GetById(valor);
        //}

        #endregion
                

        /// <summary>
        /// Gets the identificacion documento garantia.
        /// </summary>
        /// <returns></returns>
        public override string GetIdentificacionDocumentoGarantia()
        {
            //return this.NroIncidenteWorkflow;
            return this.FCCReference;

        }
        /// <summary>
        /// Sets the identificacion documento garantia.
        /// </summary>
        /// <param name="valor">The valor.</param>
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            //this.NroIncidenteWorkflow = valor;
            this.FCCReference = valor;
        }

        

        /// <summary>
        /// (buscar linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial")
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorMercado != null && this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;

        }
        /// <summary>
        /// Sets the valor garantia super intendencia.
        /// </summary>
        /// <param name="valor">The valor.</param>
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorMercado = valor;

        }
    }
}

