//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bladex.Garantias.DomainModel.Services;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa una Garantía Deposito efectuada en Otro Banco.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaDepositoOtroBanco : GarantiaBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaDepositoOtroBanco"/> class.
        /// </summary>
        public GarantiaDepositoOtroBanco() : base()
        {
            //CategoriaSuperService srv = new CategoriaSuperService();
            //this.CategoriaSuper = srv.GetById(CategoriaSuper.DEPOSITO_OTROS_ID);


        }

        /// <summary>
        /// Gets or sets the banco super.
        /// </summary>
        /// <value>
        /// The banco super.
        /// </value>
        public virtual Bancos BancoSuper
        {
            get;
            set;
        }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        #region Old GetNombreOrganismo code

        ///// <summary>
        ///// Gets the nombre organismo.
        ///// </summary>
        ///// <returns></returns>
        //public override string GetNombreOrganismo()
        //{
        //    if (this.BancoSuper == null) return string.Empty;
        //    if (this.BancoSuper.IsDirty && this.BancoSuper.Key != null)
        //    {
        //        this.SetNombreOrganismo(this.BancoSuper.Key.ToString());
        //    }
        //    // Reemplazo linea, originalmente se retornaba el Key, cambia por el nombre.
        //    return !string.IsNullOrEmpty(this.BancoSuper.Nombre) ? this.BancoSuper.Nombre.ToString() : string.Empty;
        //}
        ///// <summary>
        ///// Sets the nombre organismo.
        ///// </summary>
        ///// <param name="valor">The valor.</param>
        //public override void SetNombreOrganismo(string valor)
        //{
        //    if (string.IsNullOrEmpty(valor)) return;
        //    BancosService srv = new BancosService();
        //    this.BancoSuper = srv.GetById(valor);
        //}

        #endregion

        /// <summary>
        /// Gets the identificacion documento garantia.
        /// </summary>
        /// <returns></returns>
        public override string GetIdentificacionDocumentoGarantia()
        {
            //return this.NroIncidenteWorkflow;
            //return this.FCCReference;
            //Ticket#1550 : Se modifica el campo a pedido de Sergio Bribiesca

            return this.NumeroPolizaSeguro;
        }
        /// <summary>
        /// Sets the identificacion documento garantia.
        /// </summary>
        /// <param name="valor">The valor.</param>
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            //this.NroIncidenteWorkflow = valor;
            //this.FCCReference = valor;
            //Ticket#1550 : Se modifica el campo a pedido de Sergio Bribiesca
            
            this.NumeroPolizaSeguro = valor;
        }


        /// <summary>
        /// (buscar linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial")
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorMercado != null && this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;
        }
        /// <summary>
        /// Sets the valor garantia super intendencia.
        /// </summary>
        /// <param name="valor">The valor.</param>
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorMercado = valor;
        }
    }
}

