//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bladex.Garantias.DomainModel.Services;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa una Garantía Prendaria.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaPrenda : GarantiaBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaPrenda"/> class.
        /// </summary>
        public GarantiaPrenda():base()
        {
            //CategoriaSuperService srv = new CategoriaSuperService();
            //this.CategoriaSuper = srv.GetById(CategoriaSuper.PRENDARIA_ID);
            this.PaisEmision = new Pais();
            this.Emisor = new Actor();
            this.TipoInstrumentoFinanciero = new InstrumentoFinanciero();
            this.CalificacionEmision = new CalificacionesRiesgo();
            this.CalificacionEmisor = new CalificacionesRiesgo();
        }
        private Actor _emisor = new Actor();
        public virtual Actor Emisor
        {
            get { return _emisor; }
            set { _emisor = value; }
        }

        public virtual Pais PaisEmision
        { get; set; }

        /// <summary>
        /// codigo Catalogo SB13 (aplica solo prenda)
        /// </summary>
        public virtual InstrumentoFinanciero TipoInstrumentoFinanciero
        {
            get;
            set;
        }

        /// <summary>
        /// codigo catalog SB25 (aplica solo prenda)
        /// </summary>
        public virtual CalificacionesRiesgo CalificacionEmision
        {
            get;
            set;
        }

        /// <summary>
        /// codigo catalog SB25 (aplica solo prenda)
        /// </summary>
        public virtual CalificacionesRiesgo CalificacionEmisor
        {
            get;
            set;
        }

        /// <summary>
        /// Identificador de Prenda
        /// </summary>
        public virtual string IdentificadorPrenda
        { get; set; }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha Inicial del Avaluo
        /// </summary>
        public DateTime? FechaInicialAvaluo
        { get; set; }

        /// <summary>
        /// Fecha Vencimiento Avaluo
        /// </summary>
        public DateTime? FechaVencimientoAvaluo
        { get; set; }

        /// <summary>
        /// Valor Total Avaluo
        /// </summary>
        public Decimal ValorTotalAvaluo
        { get; set; }


        #region Old GetNombreOrganismo code

        //public override string GetNombreOrganismo()
        //{
        //    if (this.Emisor == null) return string.Empty;
        //    if (this.Emisor.IsDirty)
        //    {
        //        if (this.Emisor.Key == null) return string.Empty;
        //        SetNombreOrganismo(this.Emisor.Nombre);
        //    }

        //    return string.IsNullOrEmpty(this.Emisor.Nombre) ? string.Empty : this.Emisor.Nombre ;
        //}
        //public override void SetNombreOrganismo(string valor)
        //{
        //    if (string.IsNullOrEmpty(valor)) return;
        //    ActorService srv = new ActorService();
        //    this.Emisor = srv.GetByName(valor);
        //}

        #endregion

        public override string GetIdentificacionDocumentoGarantia()
        {
            return this.IdentificadorPrenda;

        }
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            this.IdentificadorPrenda = valor;
        }

        /// <summary>
        /// (buscar linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial")
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorMercado != null && this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;
        }
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorMercado = valor;
        }
    }
}

