//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bladex.Garantias.DomainModel.Services;
namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa una Garantia Mueble.
    /// Especializacion de <see cref="GarantiaBase"/>
    /// </summary>
    public class GarantiaMueble : GarantiaBase
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaMueble"/> class.
        /// </summary>
        public GarantiaMueble():base()
        {
        }

        /// <summary>
        /// Mueble
        /// Código que identifica el Nombre de la Aseguradora según la tabla SB57  
        /// (Aseguradoras)
        /// 
        /// Inmueble
        /// Código que identifica el Nombre del avaluador de la Finca según la tabla SB58 
        /// (Avaluadoras)
        /// 
        /// Resto:
        /// N/A
        /// </summary>
        public virtual Aseguradoras AseguradorSuper
        {
            get;
            set;
        }

        public virtual int? selectedOperationId
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha Inicial del Avaluo
        /// </summary>
        public DateTime? FechaInicialAvaluo
        { get; set; }

        /// <summary>
        /// Fecha Vencimiento Avaluo
        /// </summary>
        public DateTime? FechaVencimientoAvaluo
        { get; set; }

        /// <summary>
        /// Valor Total Avaluo
        /// </summary>
        public Decimal ValorTotalAvaluo
        { get; set; }


        #region Old GetNombreOrganismo code

        //public override string GetNombreOrganismo()
        //{
        //    if (this.AseguradorSuper == null || this.AseguradorSuper.IsDirty)
        //    {
        //        if (this.AseguradorSuper == null) return string.Empty;
        //        if (this.AseguradorSuper.Key == null) return string.Empty;

        //        this.SetNombreOrganismo(this.AseguradorSuper.Key.ToString());
        //    }
        //    return this.AseguradorSuper.Nombre;
        //}
        //public override void SetNombreOrganismo(string valor)
        //{
        //    AseguradorasService srv = new AseguradorasService();
        //    var result = srv.GetById(valor);
        //    if (result != null)
        //        this.AseguradorSuper = result;
        //    if (this.AseguradorSuper == null)
        //    {
        //        this.AseguradorSuper = AseguradorasService.GetEmpty();
        //    }
        //}

        #endregion

        public override string GetIdentificacionDocumentoGarantia()
        {
            return this.NumeroPolizaSeguro;

        }
        public override void SetIdentificacionDocumentoGarantia(string valor)
        {
            this.NumeroPolizaSeguro = valor;
            //this.NroIncidenteWorkflow = valor;
            this.FCCReference = valor;
        }

        /// <summary>
        /// Valor de Cobertura de la Póliza  (buscar linea 62 "Valor poliza seguro", en su falta linea 64 "Valor Mercado/Ultima Revisión", en su falta linea 27 "Valor Inicial"  )
        /// </summary>
        /// <returns></returns>
        public override Decimal GetValorGarantiaSuperIntendencia()
        {
            if (this.ValorPolizaSeguro != null && this.ValorPolizaSeguro != 0)
            {
                return this.ValorPolizaSeguro;
            }
            else if (this.ValorMercado != null && this.ValorMercado != 0)
            {
                return this.ValorMercado;
            }

            return this.ValorInicial;
        }
        public override void SetValorGarantiaSuperIntendencia(Decimal valor)
        {
            this.ValorPolizaSeguro = valor;
        }
    }
}

