//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Bladex.Garantias.DomainModel.Services;
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Abstract class used to represent a garantia base. 
    /// </summary>
    public abstract class GarantiaBase : EntityBase, IGarantiaFunciones
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GarantiaBase"/> class.
        /// </summary>
        protected GarantiaBase()
        {
            this.Cliente = new Cliente();
            this.FiduciariaSuper = new Fiduciarias();
            this.FrecuenciaRevision = new Frecuencias();
            this.Administrador = new Actor();
            this.Asegurador = new Actor();
            this.CategoriaRiesgoGarantia = new CategoriaRiesgoGarantia();
            this.Depositante = new Actor();
            this.Evaluador = new Actor();
            this.Garante = new Cliente();
            this.Moneda = new Monedas();
            this.PaisGarantia = new Pais();
            this.RatingGarante = new CalificacionesRiesgo();
            this.Revisor = new Actor();
            this.InternalStatus = new InternalStatusService().GetActiveStatus();
            this.Status = new StatusService().GetNormalStatus();
            this.TipoGarantiaBladex = new TipoGarantiaBladex();
            this.TipoGarantiaSuper = new TipoGarantiaSuper();
            this.Source = default(GarantiaSourceEnum);
            this.IndAtomo = IndicadorAtomoEnum.Atomo;
            this.Region = new Region();
            this.TipoPoliza = new TipoPoliza();
            
        }

        /// <summary>
        ///  referencia de FCC por migracion
        /// </summary>
        public virtual string FCCReference
        {
            get;
            set;
        }

        #region IdentificadorGarantia replaced by NroIncidenteWorkflow

        ///// <summary>
        ///// Numero de identificación/registro/certificado/notario conforme la garantía
        ///// </summary>
        //public virtual string IdentificadorGarantia
        //{
        //    get;
        //    set;
        //}

        #endregion


        /// <summary>
        /// Gets or sets the nro incidente workflow. Para las garantias provenientes de TEINSA se coloca "N/A".
        /// </summary>
        /// <value>
        /// The nro incidente workflow of type <see cref="System.String"/>
        /// </value>
        public virtual string NroIncidenteWorkflow
        {
            get;
            set;
        }

        /// <summary>
        /// 027 - el numero que asigno la super 
        /// </summary>
        public virtual string CodigoBanco
        {
            get;
            set;
        }

        /// <summary>
        /// Cliente quien aplica la garantia
        /// </summary>
        public Cliente Cliente
        {
            get;
            set;
        }

        /// <summary>
        ///   Utilizado para representar el valor por defecto de la propiedad <see cref="Beneficiario"/>
        /// </summary>
        protected string _beneficiario = "BLADEX";
        /// <summary>
        /// Beneficiario de la garantia. Similar a cliente pero creado debido a la distincion del Atomo de Garantias
        /// </summary>
        public String Beneficiario
        {
            set 
            { 
                _beneficiario = value; 
            }
            get 
            {
                return _beneficiario; 
            }
        }

        /// <summary>
        /// Cedula o RUC de la empresa (SUPER)
        /// </summary>
        public virtual string IdentificacionFideicomiso
        {
            get;
            set;
        }

        /// <summary>
        /// Codigo catalogo SB56 (Fiduciarias)
        /// </summary>
        public virtual Fiduciarias FiduciariaSuper
        {
            get;
            set;
        }

        /// <summary>
        /// Informacion interna de la ficuciaria
        /// </summary>
        public virtual string FiduciariaBladex
        {
            get;
            set;
        }

        /// <summary>
        /// Nombre Depositante/Custodio/Fiel
        /// </summary>
        public virtual Actor Depositante
        {
            get;
            set;
        }

        /// <summary>
        /// Nombre Evaluador
        /// </summary>
        public virtual Actor Evaluador
        {
            get;
            set;
        }

        /// <summary>
        /// Nombre Administrador
        /// </summary>
        public virtual Actor Administrador
        {
            get;
            set;
        }

        public virtual Actor Asegurador
        {
            get;
            set;
        }

        public virtual Actor Revisor
        {
            get;
            set;
        }

        /// <summary>
        /// Local (L)/Extrangero (E) (si es panama es local)
        /// </summary>
        private string _OrigenGarantia;
        public virtual string OrigenGarantia
        {
            get
            {
                return _OrigenGarantia;
            }
            set
            {
                if (!string.IsNullOrEmpty(value))
                {
                    if (value.Length > 1)
                    {
                        value = value.Substring(0, 1).ToUpper();
                    }
                    if (value == "" || (value != "L" && value != "E"))
                    {
                        throw new ApplicationException("Invalid OrigenGarantia. Must be L or E (Local or Extranjero)");
                    }
                    _OrigenGarantia = value;
                }
            }
        }

        /// <summary>
        /// Se debe colocar donde se encuentra fisicamente la garantia o garante
        /// </summary>
        public virtual Pais PaisGarantia
        {
            get;
            set;
        }

        /// <summary>
        /// Se debe colocar donde se encuentra fisicamente la garantia o garante
        /// </summary>
        public virtual Region Region
        {
            get;
            set;
        }

        /// <summary>
        /// El tipo de poliza
        /// </summary>
        public virtual TipoPoliza TipoPoliza
        {
            get;
            set;
        }

        /// <summary>
        /// Catalogo SB59 *opcional en caso que las garantias no posea categorizacion. Si no posee codigo no se registra contablemente
        /// 
        /// Constraint: TipoGarantiaSuper.Categoria.Id == 
        /// </summary>
        private TipoGarantiaSuper _tipoGarantiaSuper;

        public virtual TipoGarantiaSuper TipoGarantiaSuper
        {
            get
            {
                return _tipoGarantiaSuper;
            }
            set
            {
                if (value != null && value.Categoria != this.CategoriaSuper && !value.IsDirty)
                {
                    //throw new ApplicationException("Invalid TipoGarantiaSuper. Must be a category " + this.CategoriaSuper.Nombre);
                }
                if (value != null)
                    value.Categoria = this.CategoriaSuper;

                _tipoGarantiaSuper = value;
            }
        }

        /// <summary>
        /// Tipo de garantia asignada por bladex cuando no existe clasificacion
        /// 
        /// Restriccion: this.TipoGarantiaSuper.Categoria.Id == this.CategoriaSuper.Id
        /// 
        /// </summary>
        public virtual TipoGarantiaBladex TipoGarantiaBladex
        {
            get;
            set;
        }

        public virtual Decimal ValorInicial
        {
            get;
            set;
        }

        /// <summary>
        /// detalla el activo dado en garantía. Ej: , hipoteca: “inmueble industrial, ubicado … , tantos metros de área, etcétera..”, prenda de inventarios: “nro de sacas de café de 60kgs, tipo xxxx, bebida xxxx, etecétera”…
        /// </summary>
        public virtual string DescripcionDeLaGarantia
        {
            get;
            set;
        }

        public virtual Cliente Garante
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha de registro inicial de la garantía (Issue Date)
        /// </summary>
        public virtual DateTime? FechaRegistroInicial
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha de formalizacion de la garantia (Efective Date)
        /// </summary>
        public virtual DateTime? FechaFormalizacion
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha Vencimiento Riesgo Garantizado (ClousureDate)
        /// </summary>
        public virtual DateTime? FechaVencimientoRiesgo
        {
            get;
            set;
        }

        /// <summary>
        /// Fecha Vencimiento  de la Garantía (Expiry Date)
        /// </summary>
        public virtual DateTime? FechaVencimientoGarantia
        {
            get;
            set;
        }

        public virtual DateTime? FechaUltimaRevisionEvaluacion
        {
            get;
            set;

        }

        public virtual DateTime? FechaProximaRevisionEvaluacion
        {
            get
            {
                if (this.FrecuenciaRevision != null && this.FrecuenciaRevision.Key != null)
                {
                    return GarantiaBase.FechaProximaRevisionEvaluacionCalculator(this.FrecuenciaRevision.GetKeyAs<string>(), this.FechaUltimaRevisionEvaluacion);
                }
                else
                {
                    return default(DateTime?);
                }
            }
        }

        /// <summary>
        /// Calculo de FechaProximaRevisionEvaluacion
        /// </summary>
        /// <param name="frecuenciaRevisionId">The frecuencia revision id of type <see cref="System.String"/></param>
        /// <param name="fechaUltimaRevisionEvaluacion">The fecha ultima revision evaluacion of type <see cref="DateTime"/></param>
        /// <returns></returns>
        public static DateTime? FechaProximaRevisionEvaluacionCalculator(string frecuenciaRevisionId, DateTime? fechaUltimaRevisionEvaluacion)
        {
            DateTime? result = default(DateTime?);
            var frecuenciaRevision = new FrecuenciasService().GetById(frecuenciaRevisionId);
            if (fechaUltimaRevisionEvaluacion.HasValue && frecuenciaRevision != null && frecuenciaRevision.Unidad.HasValue)
            {
                switch (frecuenciaRevision.Unidad.Value)
                {
                    case UnidadFrecuenciaEnum.Days:
                        result = fechaUltimaRevisionEvaluacion.Value.AddDays(frecuenciaRevision.ValorFrecuencia);
                        break;
                    case UnidadFrecuenciaEnum.Months:
                        result = fechaUltimaRevisionEvaluacion.Value.AddMonths(frecuenciaRevision.ValorFrecuencia);
                        break;
                    case UnidadFrecuenciaEnum.Years:
                        result = fechaUltimaRevisionEvaluacion.Value.AddYears(frecuenciaRevision.ValorFrecuencia);
                        break;
                    default:
                        break;

                }
            }
            return result;
        }

        public virtual Frecuencias FrecuenciaRevision
        {
            get;
            set;
        }

        public virtual DateTime? FechaVencimientoSeguro
        {
            get;
            set;
        }

        /// <summary>
        /// Catalogo Categoria Garantias Riesgo
        /// </summary>
        public virtual CategoriaRiesgoGarantia CategoriaRiesgoGarantia
        {
            get;
            set;
        }

        public virtual decimal ReduccionDeRiesgoPorPais
        {
            get;
            set;
        }

        public virtual Monedas Moneda
        {
            get;
            set;
        }

        /// <summary>
        ///  (Necessary Value) Suma de todos las coberturas que tiene relacionadas de los prestamos
        /// </summary>
        public virtual Decimal ValorNecesarioDeGarantia
        {
            get;
            set;
        }



        public virtual Decimal PorcentajeAplicableMitigacionSuperInt
        {
            get;
            set;
        }

        public virtual string Comentarios
        {
            get;
            set;
        }

        /// <summary>
        /// Tabla SB25
        /// </summary>
        public virtual CalificacionesRiesgo RatingGarante
        {
            get;
            set;
        }

        public virtual Decimal ValorPolizaSeguro
        {
            get;
            set;
        }

        public virtual string NumeroPolizaSeguro
        {
            get;
            set;
        }

        /// <summary>
        /// Valor de Mercado ultima revision
        /// </summary>
        public virtual Decimal ValorMercado
        {
            get;
            set;
        }

        /// <summary>
        /// Guarda la categoria de la super. es importante ya que toda la logica de campo se rige de este valor.
        /// </summary>
        public virtual CategoriaSuper CategoriaSuper
        {
            get
            {
                return CategoriaSuperResolver.Resolve(this);
            }
        }

        public virtual bool? AttachedToLine
        {
            get;
            set;
        }


        public virtual int ID_Atomo
        {
            get;
            set;
        }

        /// <summary>
        /// Estatus de la garantia.
        /// Aqui se implementara si esta activa, borrada, locked, etc
        /// </summary>
        public virtual InternalStatus InternalStatus
        {
            get;
            set;
        }


        /// <summary>
        /// Status de la garancia.
        /// </summary>
        /// <value>
        /// The status - NORMAL, EN EJECUCION, EJECUTADA.
        /// </value>
        public virtual Status Status
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the fecha comienzo ejecucion.
        /// </summary>
        /// <value>
        /// The fecha comienzo ejecucion.
        /// </value>
        public virtual DateTime? FechaComienzoEjecucion 
        { 
            get; 
            set; 
        }

        /// <summary>
        /// Gets or sets the fecha cierre ejecucion.
        /// </summary>
        /// <value>
        /// The fecha cierre ejecucion.
        /// </value>
        public virtual DateTime? FechaCierreEjecucion
        {
            get;
            set;
        }

        /// <summary>
        /// Se mapea en esta propiedad el Indicador Atomo proveniente de Teinsa
        /// que indica si la garantia es:
        /// 1 - ATOMO
        /// 2 - PIGNORADOS
        /// 3 - NO ESTA EN ATOMO
        /// </summary>
        public IndicadorAtomoEnum IndAtomo
        {
            get;
            set;
        }

        /// <summary>
        /// Indica la fuente de la garantia
        /// 0 - Interna
        /// 1 - Teinsa
        /// 
        /// Esta propiedad es importante para la herramienta de sincronizacion ya que permite
        /// distinguir y no eliminar las garantias que son creadas en el modulo y que no estan
        /// en el atomo
        /// </summary>
        public GarantiaSourceEnum? Source
        {
            get;
            set;
        }

        /// <summary>
        /// Gets the identificacion documento garantia.
        /// </summary>
        /// <returns></returns>
        public abstract string GetIdentificacionDocumentoGarantia();
        /// <summary>
        /// Sets the identificacion documento garantia.
        /// </summary>
        /// <param name="valor">The valor of type <see cref="System.String"/></param>
        public abstract void SetIdentificacionDocumentoGarantia(string valor);

        /// <summary>
        /// Gets the nombre organismo.
        /// </summary>
        /// <returns></returns>
        public string NombreOrganismo { get; set; }

        #region Old GetNombreOrganismo code
        //public abstract void SetNombreOrganismo(string valor);
        #endregion

        /// <summary>
        /// Gets the valor garantia super intendencia.
        /// </summary>
        /// <returns></returns>
        public abstract Decimal GetValorGarantiaSuperIntendencia();
        /// <summary>
        /// Sets the valor garantia super intendencia.
        /// </summary>
        /// <param name="valor">The valor of type <see cref="System.Decimal"/></param>
        public abstract void SetValorGarantiaSuperIntendencia(Decimal valor);

        /// <summary>
        ///  Distressed Sale Value (En caso de no especificarse utiliza el ValorMercado y en su defecto el el ValorInicial) / ValorNecesario
        /// </summary>
        /// <returns></returns>
        public virtual Double GetRatioCoberturaGarantia()
        {
            if (this.ValorNecesarioDeGarantia == 0)
                return 0;

            // Commented after removal of ValorEvaluacionVentaRapida from GarantiaBase
            //if ( this.ValorEvaluacionVentaRapida != 0)
            //{
            //    return (double) this.ValorEvaluacionVentaRapida / (double) this.ValorNecesarioDeGarantia;
            //}
            //else 
            if (this.ValorMercado != 0)
            {
                return (double)this.ValorMercado / (double)this.ValorNecesarioDeGarantia;
            }

            return (double)this.ValorInicial / (double)this.ValorNecesarioDeGarantia;

        }




    }
}

