//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Bladex.Garantias.Infrastructure.DomainBase;


namespace Bladex.Garantias.DomainModel.DomainBase
{

    /// <summary>
    /// Clase que representa la tabla Import
    /// </summary>
    public class IMPORT_TH_ATOMO_GARANTIAS : EntityBase
    {
        public virtual int ID
        {
            get;
            set;
        }

        public virtual DateTime Fecha_corte
        {
            get;
            set;
        }

        public virtual string FECHA_SIB
        {
            get;
            set;
        }

        public virtual string CODIGO_BANCO
        {
            get;
            set;
        }

        public virtual string RUC_DEUDOR
        {
            get;
            set;
        }

        public virtual string IDENTIFICACION_FIDEICOMISO
        {
            get;
            set;
        }

        public virtual string NOMBRE_FIDUCIARIA
        {
            get;
            set;
        }

        public virtual string ORIGEN_GARANTIA
        {
            get;
            set;
        }

        public virtual string TIPO_GARANTIA
        {
            get;
            set;
        }

        public virtual string IDENTIFICACION_GARANTIA
        {
            get;
            set;
        }

        public virtual string NOMBRE_ORGANISMO
        {
            get;
            set;
        }

        public virtual Decimal VALOR_INICIAL
        {
            get;
            set;
        }

        public virtual Decimal VALOR_GARANTIA
        {
            get;
            set;
        }

        public virtual string TIPO_INSTRUMENTO
        {
            get;
            set;
        }

        public virtual string CALIFICACION_INSTRUMENTO
        {
            get;
            set;
        }

        public virtual string CALIFICACION_EMISION
        {
            get;
            set;
        }

        public virtual string PAIS_EMISION
        {
            get;
            set;
        }

        public virtual string FECHA_ULTIMA_ACT
        {
            get;
            set;
        }

        public virtual string FECHA_VENCIMIENTO
        {
            get;
            set;
        }

        public virtual string id_sib
        {
            get;
            set;
        }

        public virtual string numero_prestamo
        {
            get;
            set;
        }

        public virtual string cliente_garantia
        {
            get;
            set;
        }

        public virtual string nombre_cliente_garantia
        {
            get;
            set;
        }

        public virtual string cliente_prestamo
        {
            get;
            set;
        }

        public virtual string nombre_cliente_prestamo
        {
            get;
            set;
        }

        public virtual string APLICANTE
        {
            get;
            set;
        }

        public virtual string BENEFICIARIO
        {
            get;
            set;
        }

        public virtual string ORIGEN_TRANS
        {
            get;
            set;
        }

        public virtual string IND_ATOMO
        { get; set; }

        /// <summary>
        /// Issue Date (Come from FCC)
        /// </summary>
        public virtual DateTime? DEAL_STAT_FROM_DT
        { get; set; }

        /// <summary>
        /// Closure Date (Come from FCC)
        /// </summary>
        public virtual DateTime? DEAL_CLOSURE_DATE
        { get; set; }

        /// <summary>
        /// Effective Date (Come from FCC)
        /// </summary>
        public virtual DateTime? EFFECTIVE_DATE
        { get; set; }
    }

}
