//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa el estado de una garantía.
    /// Posibles estados: 
    /// Active
    /// Blocked
    /// Deleted (garantías con este estado no se eliminan del repositorio, solo dejan de formar parte del sistema.)
    /// </summary>
    public class InternalStatus : EntityBase
    {

        /// <summary>
        /// 
        /// </summary>
        public const string ACTIVE_ID = "1";
        /// <summary>
        /// 
        /// </summary>
        public const string DELETED_ID = "2";
        /// <summary>
        /// 
        /// </summary>
        public const string BLOCKED_ID = "3";

        public const string EXPIRED_ID = "4";

        public const string UNKNOWN_ID = "5";

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

    }
}

