//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    /// <summary>
    /// Representa un Pais dado por la super intendencia.
    /// </summary>
    public class Pais : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Codigo super intendencia para paises. Tabla SB03
        /// </summary>
        public virtual string CodigoSuper
        {
            get;
            set;
        }

    }
}

