//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bladex.Garantias.Infrastructure.DomainBase;

namespace Bladex.Garantias.DomainModel.DomainBase
{
    ///<summary>
    /// Representa el catalogo SB59 de la Super Intendencia.
    /// Cada tipo de garantía equivale a una especializacion de <see cref="GarantiaBase"/>.
    /// </summary>
    /// <remarks>SB59 Super</remarks>
    public class TipoGarantiaSuper : EntityBase
    {

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual string Nombre
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the <see cref="CategoriaSuper"/>
        /// </summary>
        /// <value>
        /// The <see cref="CategoriaSuper"/>
        /// </value>
        public virtual CategoriaSuper Categoria
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the nombre.
        /// </summary>
        /// <value>
        /// The nombre.
        /// </value>
        public virtual bool IsActive
        {
            get;
            set;
        }
    }
}

