using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bladex.Garantias.Application.Facades;
using Bladex.Garantias.DomainModel.Components.Resolvers;
using Bladex.Garantias.DomainModel.DomainBase;
using Bladex.Garantias.Infrastructure.UI.AutoMapper;
using Bladex.Garantias.Presentation.Website.Models;
using Bladex.Garantias.Presentation.Website.ViewModels;
using Bladex.Garantias.DomainModel.Components.Formatters;
using Bladex.Garantias.DomainModel.DomainBase.Components.AvalManager;

namespace Bladex.Garantias.Presentation.Website
{
    /// <summary>
    /// The web bootstrapper class.
    /// </summary>
    public static class Bootstrapper
    {
        /// <summary>
        /// Setups this instance.
        /// </summary>
        public static void Setup()
        {
            System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-us");
            System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-us");

            SetupAutomapper();
            AutoMapper.Mapper.AssertConfigurationIsValid();

            SetupLoggingFramework();
        }

        private static void SetupLoggingFramework()
        {
            //log4net.Config.XmlConfigurator.ConfigureAndWatch(new System.IO.FileInfo("log4net.config"));
            //log4net.Config.XmlConfigurator.ConfigureAndWatch(new System.IO.FileInfo("./log4net.config"));
            log4net.Config.XmlConfigurator.Configure();
        }


        /// <summary>
        /// Setups the automapper.
        /// </summary>
        private static void SetupAutomapper()
        {

            // Aca se crean los mapeos entre view models y entidades.
            AutoMapper.Mapper.CreateMap<DateTime, DateTime?>().ConvertUsing(new DateTimeTypeConverter());
            AutoMapper.Mapper.CreateMap<IndicadorAtomoEnum, IndicadorAtomoEnum?>().ConvertUsing(new EnumTypeConverter());

            #region Map of Entities View Models

            AutoMapper.Mapper.CreateMap<GarantiaContratoDealReference, DealReferenceSelectionViewModel>()
                .ForMember(o => o.FechaRegistroInicial, opt => opt.AddFormatter<DateFormatter>())
                .ForMember(o => o.FechaVencimientoGarantia, opt => opt.AddFormatter<DateFormatter>())
                .ForMember(o => o.FechaVencimientoRiesgo, opt => opt.AddFormatter<DateFormatter>())
                .ForMember(o => o.GrupoEconomico, opt => opt.MapFrom(dst => dst.GrupoEconomico))
                .ForMember(o => o.NetBalance, opt => opt.MapFrom(dst=>dst.NetBalance))
                .ForMember(o => o.NetBalanceFormatted, opt => { opt.AddFormatter<MoneyFormatter>(); opt.MapFrom(dst => dst.NetBalance); });

            AutoMapper.Mapper.CreateMap<DealReferenceSelectionViewModel, GarantiaContratoDealReference>()
                .ForMember(o => o.FechaRegistroInicial, opt => opt.ResolveUsing<DateResolver>().FromMember(o => o.FechaRegistroInicial))
                .ForMember(o => o.FechaVencimientoGarantia, opt => opt.ResolveUsing<DateResolver>().FromMember(o => o.FechaVencimientoGarantia))
                .ForMember(o => o.FechaVencimientoRiesgo, opt => opt.ResolveUsing<DateResolver>().FromMember(o => o.FechaVencimientoRiesgo))
                .ForMember(o => o.NetBalance, opt => opt.MapFrom(dst=>dst.NetBalance))
                .ForMember(o => o.GrupoEconomico, opt => opt.MapFrom(dst => dst.GrupoEconomico))
                .ForMember(o => o.Customer, opt => opt.Ignore())
                .ForMember(o => o.Key, opt => opt.MapFrom(o => o.DealReference))
                .ForMember(o => o.IsDirty, opt => opt.UseValue(true))
                .ForMember(o => o.KeyAutoGenerated, opt => opt.UseValue(false))
                .ForMember(o => o.NetBalance, opt => { opt.AddFormatter<MoneyFormatter>(); opt.ResolveUsing<MoneyResolver>().FromMember(o => o.NetBalance); });

            AutoMapper.Mapper.CreateMap<GarantiaContrato, GarantiaContratoModel>()
                .ForMember(dest => dest.PorcUtilization, opt => opt.MapFrom(dst => dst.PorcUtilization.HasValue ? dst.PorcUtilization.Value : 0));
            AutoMapper.Mapper.CreateMap<GarantiaContratoModel, GarantiaContrato>()
                .ForMember(o=>o.Key, opt=>opt.MapFrom(dst=>dst.ID))
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IsDirty, src => src.UseValue(true));

            AutoMapper.Mapper.CreateMap<LimitInformation, LimitInformationModel>()
                .ForMember(dest => dest.ExpirationDate, opt => opt.MapFrom(dst => dst.ExpirationDate.ToShortDateString()))
                .ForMember(o => o.LastLimit, opt => { opt.MapFrom(dst => dst.LastLimit); opt.AddFormatter<MoneyFormatter>(); })
                .ForMember(o => o.LimitValue, opt => { opt.MapFrom(dst => dst.LimitValue); opt.AddFormatter<MoneyFormatter>(); });

            AutoMapper.Mapper.CreateMap<ClienteViewModel, Cliente>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore())
                .ForMember(dest=>dest.AccountOfficer, opt=>opt.Ignore())
                .ForMember(dest=>dest.BusinessLineDescription, opt=>opt.Ignore())
                .ForMember(dest=>dest.GlobalLineDescription, opt=>opt.Ignore())
                .ForMember(dest=>dest.IsGarante, opt=>opt.Ignore())
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
                .ForMember(dest=>dest.LimitExpDate, opt=>opt.Ignore())
                .ForMember(dest=>dest.IsActive, opt=>opt.Ignore())
                .ForMember(dest=>dest.AuthStat, opt=>opt.Ignore())
                .ForMember(dest=>dest.RecordStat, opt=>opt.Ignore())
                .ForMember(dest => dest.Pais, opt => opt.MapFrom(src => src.Pais));
            
            AutoMapper.Mapper.CreateMap<Cliente, ClienteViewModel>()
                .ForMember(o => o.List, src => src.Ignore());

            AutoMapper.Mapper.CreateMap<ActorViewModel, Actor>()
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore())
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.Pais, opt => opt.MapFrom(src => src.Pais));

            AutoMapper.Mapper.CreateMap<Actor, ActorViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.ActorService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<AvaluadorasViewModel, Avaluadoras>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore());
            AutoMapper.Mapper.CreateMap<Avaluadoras, AvaluadorasViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.AvaluadoraService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<BancosViewModel, Bancos>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<Bancos, BancosViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.BancosService.GetAll(), "Key", "Nombre")));
            
            /* -------  Aval Manager  ---------------- */
            AutoMapper.Mapper.CreateMap<AvalManagerViewModel, AvalManager>()
               .ForMember(dest => dest.TipoAvalCatalog, opt => opt.MapFrom(src => src.TipoAvalCatalog))
               .ForMember(dest => dest.PaisCatalog, opt => opt.MapFrom(src => src.PaisCatalog))
               .ForMember(dest => dest.hiddenAvales, opt => opt.MapFrom(src => src.hiddenAvales))
               .ForMember(dest => dest.KeyAutoGenerated, opt => opt.Ignore())
               .ForMember(dest => dest.IsDirty, opt => opt.Ignore())               
               .ForMember(dest => dest.AvalList, opt => opt.MapFrom(src => src.AvalList));
             
            AutoMapper.Mapper.CreateMap<AvalManager, AvalManagerViewModel>()
                .ForMember(dest => dest.TipoAvalCatalog, opt => opt.MapFrom(src => src.TipoAvalCatalog))
               .ForMember(dest => dest.PaisCatalog, opt => opt.MapFrom(src => src.PaisCatalog))
               .ForMember(dest => dest.hiddenAvales, opt => opt.MapFrom(src => src.hiddenAvales))
               .ForMember(dest => dest.Key, opt => opt.Ignore())
               .ForMember(dest => dest.Nombre, opt => opt.Ignore())               
               .ForMember(dest => dest.EsCliente, opt => opt.Ignore())
               .ForMember(dest => dest.PorcentajeCobertura, opt => opt.Ignore())
               .ForMember(dest => dest.AvalList, opt => opt.MapFrom(src => src.AvalList));            

            AutoMapper.Mapper.CreateMap<AvalViewModel, Aval>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.GarantiaId, opt => opt.MapFrom(src => src.GarantiaId))
                .ForMember(o => o.Key, opt => opt.MapFrom(src => src.Key.HasValue ? src.Key.Value : 0))
                .ForMember(o => o.Nombre, opt => opt.MapFrom(src => src.Nombre))
                .ForMember(o => o.Pais, opt => opt.MapFrom(src => src.Pais))
                .ForMember(o => o.PorcentajeCobertura, opt => opt.MapFrom(src => src.PorcentajeCobertura))
                .ForMember(o => o.TipoAval, opt => opt.MapFrom(src => src.TipoAval))
                .ForMember(o => o.IsDirty, opt=>opt.UseValue(true));
            AutoMapper.Mapper.CreateMap<Aval, AvalViewModel>()
                .ForMember(o=>o.EsCliente, opt => opt.MapFrom(src => src.EsCliente))
                .ForMember(o => o.GarantiaId, opt => opt.MapFrom(src => src.GarantiaId))
                .ForMember(o => o.Key, opt => opt.MapFrom(src => src.Key != null ? src.GetKeyAs<int>() : default(int?)))
                .ForMember(o => o.Nombre, opt => opt.MapFrom(src => src.Nombre))
                .ForMember(o => o.Pais, opt => opt.MapFrom(src => src.Pais))
                .ForMember(o => o.PorcentajeCobertura, opt => opt.MapFrom(src => src.PorcentajeCobertura))
                .ForMember(o => o.TipoAval, opt => opt.MapFrom(src => src.TipoAval))
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.AvalService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<CalificacionesRiesgoViewModel, CalificacionesRiesgo>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<CalificacionesRiesgo, CalificacionesRiesgoViewModel>()
                .ForMember(o=>o.Nombre, opt=>opt.Ignore())
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.CalificacionesRiesgoService.GetAll().OrderBy(o => o.Orden).Select(entity => new SelectListItem { Text = entity.ToString(), Value = entity.Key.ToString() }).ToList(),"Value", "Text")));


            AutoMapper.Mapper.CreateMap<CategoriaRiesgoGarantiaViewModel, CategoriaRiesgoGarantia>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore())
                .ForMember(dest => dest.Grupo, src => src.MapFrom(dst => ServiceFacade.Instance.GrupoRiesgoGarantiaService.GetById(dst.GrupoKey)));
            AutoMapper.Mapper.CreateMap<CategoriaRiesgoGarantia, CategoriaRiesgoGarantiaViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.CategoriaRiesgoGarantiaService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<CategoriaSuperViewModel, CategoriaSuper>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<CategoriaSuper, CategoriaSuperViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.CategoriaSuperService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<FiduciariasViewModel, Fiduciarias>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<Fiduciarias, FiduciariasViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.FiduciariasService.GetAll(), "Key", "Nombre")));
            



            AutoMapper.Mapper.CreateMap<FrecuenciasViewModel, Frecuencias>()
                .ForMember(dest=>dest.Unidad, opt => opt.Ignore())
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.ValorFrecuencia, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            
            AutoMapper.Mapper.CreateMap<Frecuencias, FrecuenciasViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.FrecuenciasService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<InstrumentoFinancieroViewModel, InstrumentoFinanciero>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<InstrumentoFinanciero, InstrumentoFinancieroViewModel>()
            .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.InstrumentoFinancieroService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<MonedasViewModel, Monedas>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<Monedas, MonedasViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.MonedasService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<InternalStatusViewModel, InternalStatus>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<InternalStatus, InternalStatusViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.InternalStatusService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<StatusViewModel, Status>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore());
            AutoMapper.Mapper.CreateMap<Status, StatusViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.StatusService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<TipoGarantiaBladexViewModel, TipoGarantiaBladex>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<TipoGarantiaBladex, TipoGarantiaBladexViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.TipoGarantiaBladexService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<TipoGarantiaSuperViewModel, TipoGarantiaSuper>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<TipoGarantiaSuper, TipoGarantiaSuperViewModel>()
                .ForMember(o => o.List, src => src.MapFrom(dst=> new SelectList(ServiceFacade.Instance.TipoGarantiaSuperService.GetAll(dst.Categoria.Key.ToString()), "Key", "Nombre")))
                .ForMember(dest => dest.IsActive, src => src.MapFrom(dest => dest.IsActive));
                

            AutoMapper.Mapper.CreateMap<PaisViewModel, Pais>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<Pais, PaisViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.PaisService.GetAll(), "Key", "Nombre")));

            // ticket #1619
            AutoMapper.Mapper.CreateMap<RegionViewModel, Region>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore());
            AutoMapper.Mapper.CreateMap<Region, RegionViewModel>()
                .ForMember(o => o.List, src => src.Ignore()); // ticket #1624, la carga de la lista se hace en el populatlists del base controller
                //.ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.RegionService.GetAll(), "Key", "Nombre")));

            // ticket #1619
            AutoMapper.Mapper.CreateMap<TipoPolizaViewModel, TipoPoliza>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest => dest.IsDirty, opt => opt.Ignore());
            AutoMapper.Mapper.CreateMap<TipoPoliza, TipoPolizaViewModel>()
                .ForMember(o => o.List, src => src.Ignore()); // ticket #1624, la carga de la lista se hace en el populatlists del base controller
                //.ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.TipoPolizaService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<TipoAval, TipoAvalViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.TipoAvalService.GetAll(), "Key", "Nombre")));
            AutoMapper.Mapper.CreateMap<TipoAvalViewModel, TipoAval>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());


            AutoMapper.Mapper.CreateMap<AseguradorasViewModel, Aseguradoras>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<Aseguradoras, AseguradorasViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.AseguradorasService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<CategoriaSuperViewModel, CategoriaSuper>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<CategoriaSuper, CategoriaSuperViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.CategoriaSuperService.GetAll(), "Key", "Nombre")));

            AutoMapper.Mapper.CreateMap<CategoriaSuperViewModel, CategoriaSuper>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(dest=>dest.IsDirty, opt=>opt.Ignore());
            AutoMapper.Mapper.CreateMap<CategoriaSuper, CategoriaSuperViewModel>()
                .ForMember(o => o.List, src => src.UseValue(new SelectList(ServiceFacade.Instance.CategoriaSuperService.GetAll(), "Key", "Nombre")));
            

            #endregion

            AutoMapper.Mapper.CreateMap<GarantiaDepositoModel, GarantiaDeposito>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.IsDirty, src => src.UseValue(true));


            AutoMapper.Mapper.CreateMap<GarantiaDeposito, GarantiaDepositoModel>()
                .ForMember(o=>o.BusinessError, src=>src.Ignore())
                .ForMember(o=>o.IndAtomo, src=>src.MapFrom(dst=> dst.IndAtomo))
                .ForMember(o=>o.CategoriaSuper, src => src.MapFrom(dst=>AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))));


            AutoMapper.Mapper.CreateMap<GarantiaDepositoOtroBancoModel, GarantiaDepositoOtroBanco>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.IsDirty, src => src.UseValue(true));

            AutoMapper.Mapper.CreateMap<GarantiaDepositoOtroBanco, GarantiaDepositoOtroBancoModel>()
                .ForMember(o => o.BusinessError, src => src.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.CategoriaSuper, src => src.MapFrom(dst => AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))));

            AutoMapper.Mapper.CreateMap<GarantiaInmuebleModel, GarantiaInmueble>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.IsDirty, src => src.UseValue(true));

            AutoMapper.Mapper.CreateMap<GarantiaInmueble, GarantiaInmuebleModel>()
                .ForMember(o => o.BusinessError, src => src.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.CategoriaSuper, src => src.MapFrom(dst => AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))));

            AutoMapper.Mapper.CreateMap<GarantiaMuebleModel, GarantiaMueble>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.IsDirty, src => src.UseValue(true));

            AutoMapper.Mapper.CreateMap<GarantiaMueble, GarantiaMuebleModel>()
                .ForMember(o => o.BusinessError, src => src.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.CategoriaSuper, src => src.MapFrom(dst => AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))));

            AutoMapper.Mapper.CreateMap<GarantiaOtraModel, GarantiaOtra>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IsDirty, src => src.UseValue(true))
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o=>o.Emisor, src => src.MapFrom(dst=>dst.Emisor))
                .ForMember(o => o.AvalComponent, src => src.MapFrom(dst => dst.AvalComponent))
                .ForMember(o => o.NroReferencia, src => src.MapFrom(dst => dst.NroReferencia))
                .ForMember(o => o.Avales, src => src.MapFrom(dst => dst.AvalList));
                //.ForMember(o => o.Avales, src => src.Ignore());


            AutoMapper.Mapper.CreateMap<GarantiaOtra, GarantiaOtraModel>()
                .ForMember(o => o.BusinessError, src => src.Ignore())
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.Emisor, src => src.MapFrom(dst => dst.Emisor))
                .ForMember(o => o.AvalComponent, src => src.MapFrom(dst => dst.AvalComponent))
                .ForMember(o => o.CategoriaSuper, src => src.MapFrom(dst => AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))))
                .ForMember(o => o.NroReferencia, src => src.MapFrom(dst => dst.NroReferencia))
                .ForMember(o => o.AvalList, src => src.MapFrom(dst => dst.Avales));
                //.ForMember(o => o.AvalList, src => src.Ignore());

            AutoMapper.Mapper.CreateMap<GarantiaPrenda, GarantiaPrendaModel>()
                .ForMember(o=>o.PaisEmision, src => src.MapFrom(dst=>dst.PaisEmision))
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o => o.CategoriaSuper, src => src.MapFrom(dst => AutoMapper.Mapper.Map<CategoriaSuper, CategoriaSuperViewModel>(Bladex.Garantias.DomainModel.DomainBase.CategoriaSuperResolver.Resolve(dst))))
                .ForMember(o=>o.TipoInstrumentoFinanciero, src =>src.MapFrom(dst=>dst.TipoInstrumentoFinanciero))
                .ForMember(o => o.CalificacionesRiesgoEmision, src => src.MapFrom(dst => dst.CalificacionEmision))
                .ForMember(o => o.CalificacionesRiesgoEmisor, src => src.MapFrom(dst => dst.CalificacionEmisor))
                .ForMember(o => o.BusinessError, src => src.Ignore());
            
            AutoMapper.Mapper.CreateMap<GarantiaPrendaModel, GarantiaPrenda>()
                .ForMember(o => o.KeyAutoGenerated, opt => opt.Ignore())
                .ForMember(o => o.IsDirty, src => src.UseValue(true))
                .ForMember(o => o.IndAtomo, src => src.MapFrom(dst => dst.IndAtomo))
                .ForMember(o=>o.PaisEmision, src =>src.MapFrom(dst=>dst.PaisEmision))
                .ForMember(o => o.CalificacionEmision, src=>src.MapFrom(dst=>dst.CalificacionesRiesgoEmision))
                .ForMember(o => o.CalificacionEmisor, src => src.MapFrom(dst => dst.CalificacionesRiesgoEmisor))
                .ForMember(o=>o.TipoInstrumentoFinanciero, src=>src.MapFrom(dst=>dst.TipoInstrumentoFinanciero));

        }
   }
}