ALTER TABLE [dbo].[APP_MakerChecker_OperationStatus]
    ADD CONSTRAINT [PK_APP_MakerChecker_OperationStatus] PRIMARY KEY CLUSTERED ([OperationStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

