ALTER TABLE [dbo].[APP_MakerChecker_Changeset]
    ADD CONSTRAINT [PK_APP_MakerChecker_Changeset_1] PRIMARY KEY CLUSTERED ([ChangesetID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

