ALTER TABLE [dbo].[APP_MakerChecker_EmailTemplate]
    ADD CONSTRAINT [PK_APP_MakerChecker_EmailTemplate] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

