ALTER TABLE [dbo].[GarantiaContrato_ProductFilter]
    ADD CONSTRAINT [PK_GarantiaContrato_ProductFilter] PRIMARY KEY CLUSTERED ([ProductGroupCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

