ALTER TABLE [dbo].[GarantiaInmueble]
    ADD CONSTRAINT [PK_GarantiaInmueble_1] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

