ALTER TABLE [dbo].[TH_ATOMO_GARANTIAS_History]
    ADD CONSTRAINT [PK_TH_ATOMO_GARANTIAS_History] PRIMARY KEY CLUSTERED ([BusinessDate] ASC, [ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

